-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [trait_probe]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import TraitProbe.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open trait_probe

/-- [trait_probe::external_double]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 5:20-5:54 -/
axiom external_double : Std.U32 → Result Std.U32

