-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [trait_probe]: function definitions
import Aeneas
import TraitProbe.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace trait_probe

/-- [trait_probe::{impl trait_probe::Step for u32}::step]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 3:20-3:65
    Visibility: public -/
def U32.Insts.Trait_probeStep.step (self : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add self 1#u32)

/-- Trait implementation: [trait_probe::{impl trait_probe::Step for u32}]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 3:0-3:67 -/
@[reducible]
def U32.Insts.Trait_probeStep : Step Std.U32 := {
  step := U32.Insts.Trait_probeStep.step
}

/-- [trait_probe::use_step]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 4:0-4:43
    Visibility: public -/
def use_step (x : Std.U32) : Result Std.U32 := do
  U32.Insts.Trait_probeStep.step x

/-- [trait_probe::bad]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 5:0-5:48
    Visibility: public -/
def bad (p : MutRawPtr Std.U32) : Result Std.U32 := do
  sorry

end trait_probe
