-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [trait_probe]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace trait_probe

/-- Trait declaration: [trait_probe::Step]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 2:0-2:40
    Visibility: public -/
structure Step (Self : Type) where
  step : Self → Result Std.U32

end trait_probe
