/- Copyright 2026 The Fuchsia Authors

Licensed under a BSD-style license <LICENSE-BSD>, Apache License, Version 2.0
<LICENSE-APACHE or https://www.apache.org/licenses/LICENSE-2.0>, or the MIT
license <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
This file may not be copied, modified, or distributed except according to
those terms. -/

-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zerocopy]: function definitions
module
public import Aeneas
public import Zerocopy.Types
public import Zerocopy.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace Zerocopy

/-- Trait implementation: [core::num::niche_types::{impl core::clone::Clone for core::num::niche_types::NonZeroUsizeInner}]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:17-17:22
    Name pattern: [core::clone::Clone<core::num::niche_types::NonZeroUsizeInner>] -/
@[reducible, rust_trait_impl
  "core::clone::Clone<core::num::niche_types::NonZeroUsizeInner>"]
def core.num.niche_types.NonZeroUsizeInner.Insts.CoreCloneClone :
  core.clone.Clone core.num.niche_types.NonZeroUsizeInner := {
  clone := core.num.niche_types.NonZeroUsizeInner.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [core::num::niche_types::{impl core::marker::Copy for core::num::niche_types::NonZeroUsizeInner}]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:24-17:28
    Name pattern: [core::marker::Copy<core::num::niche_types::NonZeroUsizeInner>] -/
@[reducible, rust_trait_impl
  "core::marker::Copy<core::num::niche_types::NonZeroUsizeInner>"]
def core.num.niche_types.NonZeroUsizeInner.Insts.CoreMarkerCopy :
  core.marker.Copy core.num.niche_types.NonZeroUsizeInner := {
  cloneInst := core.num.niche_types.NonZeroUsizeInner.Insts.CoreCloneClone
}

/-- Trait implementation: [core::num::nonzero::{impl core::num::nonzero::ZeroablePrimitive<core::num::niche_types::NonZeroUsizeInner> for usize}]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 47:12-47:56
    Name pattern: [core::num::nonzero::ZeroablePrimitive<usize, core::num::niche_types::NonZeroUsizeInner>] -/
@[reducible, rust_trait_impl
  "core::num::nonzero::ZeroablePrimitive<usize, core::num::niche_types::NonZeroUsizeInner>"]
def Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner :
  core.num.nonzero.ZeroablePrimitive Std.Usize
  core.num.niche_types.NonZeroUsizeInner := {
  markerCopyInst := core.marker.CopyUsize
  innerCopyInst := core.num.niche_types.NonZeroUsizeInner.Insts.CoreMarkerCopy
}

/-- [zerocopy::layout::POINTER_WIDTH_BITS]
    Source: 'src/layout.rs', lines 17:0-17:62 -/
@[global_simps, irreducible]
def layout.POINTER_WIDTH_BITS : Result Std.Usize := do
  let i ← core.mem.size_of Std.Usize
  i * 8#usize

/-- [zerocopy::layout::{zerocopy::layout::RoundingAlignAndPhase}::new]:
    Source: 'src/layout.rs', lines 77:4-103:5 -/
def layout.RoundingAlignAndPhase.new
  (align : core.num.nonzero.NonZero Std.Usize
  core.num.niche_types.NonZeroUsizeInner) (phase : Std.Usize) :
  Result layout.RoundingAlignAndPhase
  := do
  let i ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner align
  let b ← core.num.Usize.is_power_of_two i
  massert b
  massert (phase < i)
  let encoded ← lift (i ||| phase)
  let o ←
    core.num.nonzero.NonZero.new
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner encoded
  match o with
  | none => fail panic
  | some encoded1 => ok encoded1

/-- [zerocopy::layout::{zerocopy::layout::RoundingAlignAndPhase}::components]:
    Source: 'src/layout.rs', lines 111:4-143:5 -/
def layout.RoundingAlignAndPhase.components
  (self : layout.RoundingAlignAndPhase) :
  Result ((core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner) × Std.Usize)
  := do
  let i ← layout.POINTER_WIDTH_BITS
  let i1 ← i - 1#usize
  let i2 ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner self
  let i3 ← lift (core.num.Usize.leading_zeros i2)
  let i4 ← lift (UScalar.cast .Usize i3)
  let shift ← i1 - i4
  let align ← 1#usize <<< shift
  let o ←
    core.num.nonzero.NonZero.new
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner align
  match o with
  | none => fail panic
  | some align1 =>
    let i5 ←
      core.num.nonzero.NonZero.get
        Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner align1
    let phase ← lift (i2 ^^^ i5)
    ok (align1, phase)

/-- [zerocopy::layout::{zerocopy::layout::RoundingAlignAndPhase}::align]:
    Source: 'src/layout.rs', lines 151:4-166:5 -/
def layout.RoundingAlignAndPhase.align
  (self : layout.RoundingAlignAndPhase) :
  Result (core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner)
  := do
  let (nz, _) ← layout.RoundingAlignAndPhase.components self
  ok nz

/-- [zerocopy::util::round_down_to_next_multiple_of_alignment]:
    Source: 'src/util/mod.rs', lines 247:0-275:1 -/
def util.round_down_to_next_multiple_of_alignment
  (n : Std.Usize)
  (align : core.num.nonzero.NonZero Std.Usize
  core.num.niche_types.NonZeroUsizeInner) :
  Result Std.Usize
  := do
  let align1 ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner align
  let b ← core.num.Usize.is_power_of_two align1
  massert b
  let i ← align1 - 1#usize
  let mask ← lift (~~~ i)
  ok (n &&& mask)

/-- [zerocopy::layout::{zerocopy::layout::TrailingSliceLayout<E>}::size_offset]:
    Source: 'src/layout.rs', lines 240:4-260:5 -/
def layout.TrailingSliceLayout.size_offset
  {E : Type} (self : layout.TrailingSliceLayout E) : Result Std.Usize := do
  let (size_align, size_phase) ←
    layout.RoundingAlignAndPhase.components self.size_rounding_align_and_phase
  let aligned_base ←
    util.round_down_to_next_multiple_of_alignment self.size_base size_align
  ok (aligned_base ||| size_phase)

/-- [zerocopy::layout::{zerocopy::layout::TrailingSliceLayout<E>}::max_trailing_bytes]:
    Source: 'src/layout.rs', lines 278:4-373:5 -/
def layout.TrailingSliceLayout.max_trailing_bytes
  {E : Type} (self : layout.TrailingSliceLayout E)
  (available_bytes : Std.Usize) :
  Result (Option Std.Usize)
  := do
  let (size_align, size_phase) ←
    layout.RoundingAlignAndPhase.components self.size_rounding_align_and_phase
  let rounded_phase ←
    if size_phase = 0#usize
    then ok 0#usize
    else
      core.num.nonzero.NonZero.get
        Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner size_align
  let o ← lift (Usize.checked_add self.size_base rounded_phase)
  match o with
  | none => ok none
  | some size =>
    let o1 ← lift (Usize.checked_sub available_bytes size)
    match o1 with
    | none => ok none
    | some bytes =>
      let aligned_bytes ←
        util.round_down_to_next_multiple_of_alignment bytes size_align
      let initial_padding ← rounded_phase - size_phase
      let trailing_bytes ← lift (aligned_bytes ||| initial_padding)
      ok (some trailing_bytes)

/-- [zerocopy::util::padding_needed_for]:
    Source: 'src/util/mod.rs', lines 156:0-226:1 -/
def util.padding_needed_for
  (len : Std.Usize)
  (align : core.num.nonzero.NonZero Std.Usize
  core.num.niche_types.NonZeroUsizeInner) :
  Result Std.Usize
  := do
  let i ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner align
  let mask ← i - 1#usize
  let i1 ← lift (core.num.Usize.wrapping_sub len 1#usize)
  let i2 ← lift (~~~ i1)
  ok (i2 &&& mask)

/-- [zerocopy::layout::{zerocopy::layout::TrailingSliceLayout<usize>}::padding_for_elems]:
    Source: 'src/layout.rs', lines 392:4-454:5 -/
def layout.TrailingSliceLayoutUsize.padding_for_elems
  (self : layout.TrailingSliceLayout Std.Usize) (elems : Std.Usize) :
  Result Std.Usize
  := do
  let (size_align, size_phase) ←
    layout.RoundingAlignAndPhase.components self.size_rounding_align_and_phase
  let i ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner size_align
  let size_mask ← i - 1#usize
  let elem_remainder ← lift (self.elem_size &&& size_mask)
  let i1 ← lift (core.num.Usize.wrapping_mul elems elem_remainder)
  let trailing_remainder ← lift (i1 &&& size_mask)
  let rounding_input ←
    lift (core.num.Usize.wrapping_add size_phase trailing_remainder)
  let rounding_padding ← util.padding_needed_for rounding_input size_align
  let i2 ← lift (core.num.Usize.wrapping_add self.size_base size_phase)
  let i3 ← lift (core.num.Usize.wrapping_sub i2 self.offset)
  ok (core.num.Usize.wrapping_add i3 rounding_padding)

/-- [zerocopy::layout::{zerocopy::layout::TrailingSliceLayout<usize>}::size_for_elems]:
    Source: 'src/layout.rs', lines 466:4-536:5 -/
def layout.TrailingSliceLayoutUsize.size_for_elems
  (self : layout.TrailingSliceLayout Std.Usize) (elems : Std.Usize) :
  Result (Option Std.Usize)
  := do
  let o ←
    layout.TrailingSliceLayout.max_trailing_bytes self core.num.Usize.MAX
  match o with
  | none => ok none
  | some bytes =>
    let o1 ← lift (Usize.checked_mul self.elem_size elems)
    match o1 with
    | none => ok none
    | some bytes1 =>
      if bytes1 > bytes
      then ok none
      else
        let trailing_end ←
          lift (core.num.Usize.wrapping_add self.offset bytes1)
        let i ← layout.TrailingSliceLayoutUsize.padding_for_elems self elems
        let size ← lift (core.num.Usize.wrapping_add trailing_end i)
        ok (some size)

/-- [zerocopy::layout::{zerocopy::layout::TrailingSliceLayout<usize>}::has_same_size_sequence]:
    Source: 'src/layout.rs', lines 555:4-639:5 -/
def layout.TrailingSliceLayoutUsize.has_same_size_sequence
  (self : layout.TrailingSliceLayout Std.Usize)
  (other : layout.TrailingSliceLayout Std.Usize) :
  Result Bool
  := do
  if self.elem_size != other.elem_size
  then ok false
  else
    let o ← layout.TrailingSliceLayoutUsize.size_for_elems self 0#usize
    let o1 ← layout.TrailingSliceLayoutUsize.size_for_elems other 0#usize
    match o with
    | none => ok false
    | some self_size =>
      match o1 with
      | none => ok false
      | some other_size =>
        if self_size = other_size
        then
          let (self_align, self_phase) ←
            layout.RoundingAlignAndPhase.components
              self.size_rounding_align_and_phase
          let (other_align, other_phase) ←
            layout.RoundingAlignAndPhase.components
              other.size_rounding_align_and_phase
          let self_align1 ←
            core.num.nonzero.NonZero.get
              Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner
              self_align
          let other_align1 ←
            core.num.nonzero.NonZero.get
              Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner
              other_align
          let max_align ←
            if self_align1 > other_align1
            then ok self_align1
            else ok other_align1
          let i ← self.elem_size % max_align
          if i = 0#usize
          then ok true
          else
            if self_align1 != other_align1
            then ok false
            else ok (self_phase = other_phase)
        else ok false

/-- [zerocopy::layout::{zerocopy::layout::TrailingSliceLayout<usize>}::advance]:
    Source: 'src/layout.rs', lines 675:4-780:5 -/
def layout.TrailingSliceLayoutUsize.advance
  (self : layout.TrailingSliceLayout Std.Usize) (bytes : Std.Usize)
  (elem_size : Std.Usize) :
  Result (Option (layout.TrailingSliceLayout Std.Usize))
  := do
  let (size_align, size_phase) ←
    layout.RoundingAlignAndPhase.components self.size_rounding_align_and_phase
  let i ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner size_align
  let align_mask ← i - 1#usize
  let i1 ← core.num.Usize.MAX - self.size_base
  let phase_capacity ← lift (i1 ||| align_mask)
  let max_advance ← phase_capacity - size_phase
  if bytes > max_advance
  then ok none
  else
    let advanced_phase ← size_phase + bytes
    let normalized_phase ← lift (advanced_phase &&& align_mask)
    let whole_bytes ←
      util.round_down_to_next_multiple_of_alignment advanced_phase size_align
    let size_base ← self.size_base + whole_bytes
    let raap ← layout.RoundingAlignAndPhase.new size_align normalized_phase
    ok (some
      { self with elem_size, size_base, size_rounding_align_and_phase := raap })

/-- [zerocopy::layout::{zerocopy::layout::SizeInfo<usize>}::try_to_nonzero_elem_size]:
    Source: 'src/layout.rs', lines 802:4-842:5 -/
def layout.SizeInfoUsize.try_to_nonzero_elem_size
  (self : layout.SizeInfo Std.Usize) :
  Result (Option (layout.SizeInfo (core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner)))
  := do
  match self with
  | layout.SizeInfo.Sized size => ok (some (layout.SizeInfo.Sized size))
  | layout.SizeInfo.SliceDst tsl =>
    let o ←
      core.num.nonzero.NonZero.new
        Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner
        tsl.elem_size
    match o with
    | none => ok none
    | some elem_size =>
      ok (some (layout.SizeInfo.SliceDst
        {
          offset := tsl.offset,
          elem_size,
          size_base := tsl.size_base,
          size_rounding_align_and_phase := tsl.size_rounding_align_and_phase
        }))

/-- [zerocopy::layout::max_elems_for_bytes]:
    Source: 'src/layout.rs', lines 862:0-886:1 -/
def layout.max_elems_for_bytes
  (bytes : Std.Usize)
  (elem_size : core.num.nonzero.NonZero Std.Usize
  core.num.niche_types.NonZeroUsizeInner) :
  Result (Std.Usize × Std.Usize)
  := do
  let i ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner elem_size
  let elems ← bytes / i
  let o ← lift (Usize.checked_mul elems i)
  match o with
  | none => fail panic
  | some used => ok (elems, used)

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::MIN_ALIGN]
    Source: 'src/layout.rs', lines 906:4-909:6 -/
@[global_simps, irreducible]
def layout.DstLayout.MIN_ALIGN
  :
  Result (core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner)
  := do
  let o ←
    core.num.nonzero.NonZero.new
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner 1#usize
  match o with
  | none => fail panic
  | some min_align => ok min_align

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::THEORETICAL_MAX_ALIGN]
    Source: 'src/layout.rs', lines 916:4-920:10 -/
@[global_simps, irreducible]
def layout.DstLayout.THEORETICAL_MAX_ALIGN
  :
  Result (core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner)
  := do
  let i ← layout.POINTER_WIDTH_BITS
  let i1 ← i - 1#usize
  let i2 ← 1#usize <<< i1
  let o ←
    core.num.nonzero.NonZero.new
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner i2
  match o with
  | none => fail panic
  | some max_align => ok max_align

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::CURRENT_MAX_ALIGN]
    Source: 'src/layout.rs', lines 930:4-933:6 -/
@[global_simps, irreducible]
def layout.DstLayout.CURRENT_MAX_ALIGN
  :
  Result (core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner)
  := do
  let i ← 1#usize <<< 29#i32
  let o ←
    core.num.nonzero.NonZero.new
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner i
  match o with
  | none => fail panic
  | some max_align => ok max_align

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::assume_shallow_unpadded]:
    Source: 'src/layout.rs', lines 970:4-984:5 -/
def layout.DstLayout.assume_shallow_unpadded
  (self : layout.DstLayout) : Result layout.DstLayout := do
  ok { self with statically_shallow_unpadded := true }

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::new_zst]:
    Source: 'src/layout.rs', lines 1006:4-1033:5
    Visibility: public -/
def layout.DstLayout.new_zst
  (repr_align : Option (core.num.nonzero.NonZero Std.Usize
  core.num.niche_types.NonZeroUsizeInner)) :
  Result layout.DstLayout
  := do
  let align ←
    match repr_align with
    | none => layout.DstLayout.MIN_ALIGN
    | some align1 => ok align1
  let i ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner align
  let b ← core.num.Usize.is_power_of_two i
  massert b
  ok
    {
      align,
      size_info := (layout.SizeInfo.Sized 0#usize),
      statically_shallow_unpadded := true
    }

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::for_type]:
    Source: 'src/layout.rs', lines 1049:4-1082:5
    Visibility: public -/
def layout.DstLayout.for_type (T : Type) : Result layout.DstLayout := do
  let i ← core.mem.align_of T
  let o ←
    core.num.nonzero.NonZero.new
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner i
  match o with
  | none => fail panic
  | some align =>
    let i1 ← core.mem.size_of T
    ok
      {
        align,
        size_info := (layout.SizeInfo.Sized i1),
        statically_shallow_unpadded := false
      }

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::for_unpadded_type]:
    Source: 'src/layout.rs', lines 1104:4-1126:5
    Visibility: public -/
def layout.DstLayout.for_unpadded_type
  (T : Type) : Result layout.DstLayout := do
  let dl ← layout.DstLayout.for_type T
  layout.DstLayout.assume_shallow_unpadded dl

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::for_slice]:
    Source: 'src/layout.rs', lines 1140:4-1187:5 -/
def layout.DstLayout.for_slice (T : Type) : Result layout.DstLayout := do
  let i ← core.mem.align_of T
  let o ←
    core.num.nonzero.NonZero.new
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner i
  match o with
  | none => fail panic
  | some align =>
    let i1 ← core.mem.size_of T
    let raap ← layout.RoundingAlignAndPhase.new align 0#usize
    ok
      {
        align,
        size_info :=
          (layout.SizeInfo.SliceDst
            {
              offset := 0#usize,
              elem_size := i1,
              size_base := 0#usize,
              size_rounding_align_and_phase := raap
            }),
        statically_shallow_unpadded := true
      }

/-- [zerocopy::util::min]:
    Source: 'src/util/mod.rs', lines 294:0-305:1 -/
def util.min
  (a : core.num.nonzero.NonZero Std.Usize
  core.num.niche_types.NonZeroUsizeInner)
  (b : core.num.nonzero.NonZero Std.Usize
  core.num.niche_types.NonZeroUsizeInner) :
  Result (core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner)
  := do
  let i ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner a
  let i1 ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner b
  if i > i1
  then ok b
  else ok a

/-- [zerocopy::util::max]:
    Source: 'src/util/mod.rs', lines 279:0-290:1 -/
def util.max
  (a : core.num.nonzero.NonZero Std.Usize
  core.num.niche_types.NonZeroUsizeInner)
  (b : core.num.nonzero.NonZero Std.Usize
  core.num.niche_types.NonZeroUsizeInner) :
  Result (core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner)
  := do
  let i ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner a
  let i1 ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner b
  if i < i1
  then ok b
  else ok a

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::extend]:
    Source: 'src/layout.rs', lines 1297:4-1466:5
    Visibility: public -/
def layout.DstLayout.extend
  (self : layout.DstLayout) (field : layout.DstLayout)
  (repr_packed : Option (core.num.nonzero.NonZero Std.Usize
  core.num.niche_types.NonZeroUsizeInner)) :
  Result layout.DstLayout
  := do
  let max_align ←
    match repr_packed with
    | none => layout.DstLayout.THEORETICAL_MAX_ALIGN
    | some max_align1 => ok max_align1
  let i ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner max_align
  let b ← core.num.Usize.is_power_of_two i
  massert b
  let i1 ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner self.align
  let nz ← layout.DstLayout.CURRENT_MAX_ALIGN
  let i2 ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner nz
  massert (i1 <= i2)
  let i3 ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner field.align
  let i4 ←
    core.num.nonzero.NonZero.get
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner nz
  massert (i3 <= i4)
  let _ ←
    match repr_packed with
    | none => ok none
    | some repr_packed1 =>
      do
      let i5 ←
        core.num.nonzero.NonZero.get
          Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner
          repr_packed1
      let i6 ←
        core.num.nonzero.NonZero.get
          Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner nz
      massert (i5 <= i6)
      ok repr_packed
  let field_align ← util.min field.align max_align
  let align ← util.max self.align field_align
  match self.size_info with
  | layout.SizeInfo.Sized preceding_size =>
    let padding ← util.padding_needed_for preceding_size field_align
    let o ← lift (Usize.checked_add preceding_size padding)
    match o with
    | none => fail panic
    | some offset =>
      match field.size_info with
      | layout.SizeInfo.Sized field_size =>
        let o1 ← lift (Usize.checked_add offset field_size)
        match o1 with
        | none => fail panic
        | some size =>
          if self.statically_shallow_unpadded
          then
            if field.statically_shallow_unpadded
            then
              ok
                {
                  align,
                  size_info := (layout.SizeInfo.Sized size),
                  statically_shallow_unpadded := (padding = 0#usize)
                }
            else
              ok
                {
                  align,
                  size_info := (layout.SizeInfo.Sized size),
                  statically_shallow_unpadded := false
                }
          else
            ok
              {
                align,
                size_info := (layout.SizeInfo.Sized size),
                statically_shallow_unpadded := false
              }
      | layout.SizeInfo.SliceDst tsl =>
        let o1 ← lift (Usize.checked_add offset tsl.offset)
        match o1 with
        | none => fail panic
        | some offset1 =>
          let o2 ← lift (Usize.checked_add offset tsl.size_base)
          match o2 with
          | none => fail panic
          | some base =>
            if self.statically_shallow_unpadded
            then
              if field.statically_shallow_unpadded
              then
                ok
                  {
                    align,
                    size_info :=
                      (layout.SizeInfo.SliceDst
                        { tsl with offset := offset1, size_base := base }),
                    statically_shallow_unpadded := (padding = 0#usize)
                  }
              else
                ok
                  {
                    align,
                    size_info :=
                      (layout.SizeInfo.SliceDst
                        { tsl with offset := offset1, size_base := base }),
                    statically_shallow_unpadded := false
                  }
            else
              ok
                {
                  align,
                  size_info :=
                    (layout.SizeInfo.SliceDst
                      { tsl with offset := offset1, size_base := base }),
                  statically_shallow_unpadded := false
                }
  | layout.SizeInfo.SliceDst _ => fail panic

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::pad_to_align]:
    Source: 'src/layout.rs', lines 1494:4-1603:5
    Visibility: public -/
def layout.DstLayout.pad_to_align
  (self : layout.DstLayout) : Result layout.DstLayout := do
  match self.size_info with
  | layout.SizeInfo.Sized unpadded_size =>
    let padding ← util.padding_needed_for unpadded_size self.align
    let o ← lift (Usize.checked_add unpadded_size padding)
    match o with
    | none => fail panic
    | some size =>
      if self.statically_shallow_unpadded
      then
        ok
          {
            self
              with
              size_info := (layout.SizeInfo.Sized size),
              statically_shallow_unpadded := (padding = 0#usize)
          }
      else ok { self with size_info := (layout.SizeInfo.Sized size) }
  | layout.SizeInfo.SliceDst trailing =>
    let (size_align, size_phase) ←
      layout.RoundingAlignAndPhase.components
        trailing.size_rounding_align_and_phase
    let i ←
      core.num.nonzero.NonZero.get
        Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner size_align
    let i1 ←
      core.num.nonzero.NonZero.get
        Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner 
        self.align
    if i < i1
    then
      let base_padding ←
        util.padding_needed_for trailing.size_base size_align
      let o ← lift (Usize.checked_add trailing.size_base base_padding)
      match o with
      | none => fail panic
      | some base =>
        let o1 ← lift (Usize.checked_add base size_phase)
        match o1 with
        | none => fail panic
        | some bytes =>
          let i2 ← i1 - 1#usize
          let phase ← lift (bytes &&& i2)
          let size_base ←
            util.round_down_to_next_multiple_of_alignment bytes self.align
          let raap ← layout.RoundingAlignAndPhase.new self.align phase
          if self.statically_shallow_unpadded
          then
            ok
              {
                self
                  with
                  size_info :=
                    (layout.SizeInfo.SliceDst
                      {
                        trailing
                          with
                          size_base, size_rounding_align_and_phase := raap
                      }),
                  statically_shallow_unpadded := (0#usize = 0#usize)
              }
          else
            ok
              {
                self
                  with
                  size_info :=
                    (layout.SizeInfo.SliceDst
                      {
                        trailing
                          with
                          size_base, size_rounding_align_and_phase := raap
                      })
              }
    else
      let padding ← util.padding_needed_for trailing.size_base self.align
      let o ← lift (Usize.checked_add trailing.size_base padding)
      match o with
      | none => fail panic
      | some base =>
        if self.statically_shallow_unpadded
        then
          ok
            {
              self
                with
                size_info :=
                  (layout.SizeInfo.SliceDst
                    { trailing with size_base := base }),
                statically_shallow_unpadded := (0#usize = 0#usize)
            }
        else
          ok
            {
              self
                with
                size_info :=
                  (layout.SizeInfo.SliceDst
                    { trailing with size_base := base })
            }

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::requires_static_padding]:
    Source: 'src/layout.rs', lines 1615:4-1629:5
    Visibility: public -/
def layout.DstLayout.requires_static_padding
  (self : layout.DstLayout) : Result Bool := do
  ok (¬ self.statically_shallow_unpadded)

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::requires_dynamic_padding]:
    Source: 'src/layout.rs', lines 1645:4-1682:5
    Visibility: public -/
def layout.DstLayout.requires_dynamic_padding
  (self : layout.DstLayout) : Result Bool := do
  match self.size_info with
  | layout.SizeInfo.Sized _ => ok false
  | layout.SizeInfo.SliceDst trailing_slice_layout =>
    let o ←
      layout.TrailingSliceLayoutUsize.size_for_elems trailing_slice_layout
        0#usize
    match o with
    | none => ok true
    | some initial_size =>
      let nz ←
        layout.RoundingAlignAndPhase.align
          trailing_slice_layout.size_rounding_align_and_phase
      let i ←
        core.num.nonzero.NonZero.get
          Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner nz
      let i1 ← trailing_slice_layout.elem_size % i
      if initial_size != trailing_slice_layout.offset
      then ok true
      else ok (¬ (i1 = 0#usize))

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::validate_cast_and_convert_metadata]:
    Source: 'src/layout.rs', lines 1839:4-1996:5 -/
def layout.DstLayout.validate_cast_and_convert_metadata
  (self : layout.DstLayout) (addr : Std.Usize) (bytes_len : Std.Usize)
  (cast_type : layout.CastType) :
  Result (core.result.Result (Std.Usize × Std.Usize) layout.MetadataCastError)
  := do
  let o ← layout.SizeInfoUsize.try_to_nonzero_elem_size self.size_info
  match o with
  | none => fail panic
  | some size_info =>
    let o1 ← lift (Usize.checked_add addr bytes_len)
    let e := core.option.Option.is_some o1
    massert e
    let offset ←
      match cast_type with
      | layout.CastType.Prefix => ok 0#usize
      | layout.CastType.Suffix => ok bytes_len
    let i ← addr + offset
    let i1 ←
      core.num.nonzero.NonZero.get
        Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner 
        self.align
    let i2 ← i % i1
    if i2 != 0#usize
    then ok (core.result.Result.Err layout.MetadataCastError.Alignment)
    else
      match size_info with
      | layout.SizeInfo.Sized size =>
        massert ((size > bytes_len) || (size <= bytes_len))
        if size > bytes_len
        then ok (core.result.Result.Err layout.MetadataCastError.Size)
        else
          match cast_type with
          | layout.CastType.Prefix =>
            ok (core.result.Result.Ok (0#usize, size))
          | layout.CastType.Suffix =>
            let split_at ← bytes_len - size
            ok (core.result.Result.Ok (0#usize, split_at))
      | layout.SizeInfo.SliceDst trailing =>
        let o2 ←
          layout.TrailingSliceLayout.max_trailing_bytes trailing bytes_len
        match o2 with
        | none => ok (core.result.Result.Err layout.MetadataCastError.Size)
        | some bytes =>
          let (elems, _) ←
            layout.max_elems_for_bytes bytes trailing.elem_size
          let size_align ←
            layout.RoundingAlignAndPhase.align
              trailing.size_rounding_align_and_phase
          let i3 ←
            core.num.nonzero.NonZero.get
              Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner
              trailing.elem_size
          let unused_bytes ← bytes % i3
          let unused_aligned_bytes ←
            util.round_down_to_next_multiple_of_alignment unused_bytes
              size_align
          let i4 ← bytes_len - trailing.size_base
          let max_rounded_bytes ←
            util.round_down_to_next_multiple_of_alignment i4 size_align
          let i5 ← max_rounded_bytes - unused_aligned_bytes
          let self_bytes ← trailing.size_base + i5
          massert (self_bytes <= bytes_len)
          match cast_type with
          | layout.CastType.Prefix =>
            ok (core.result.Result.Ok (elems, self_bytes))
          | layout.CastType.Suffix =>
            let split_at ← bytes_len - self_bytes
            ok (core.result.Result.Ok (elems, split_at))

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::metadata_for_exact_size]:
    Source: 'src/layout.rs', lines 1700:4-1733:5 -/
def layout.DstLayout.metadata_for_exact_size
  (self : layout.DstLayout) (size : Std.Usize) :
  Result (Option Std.Usize)
  := do
  match self.size_info with
  | layout.SizeInfo.Sized _ => ok none
  | layout.SizeInfo.SliceDst tsl =>
    match tsl.elem_size.val with
    | 0 => ok none
    | _ =>
      let r ←
        layout.DstLayout.validate_cast_and_convert_metadata self 0#usize size
          layout.CastType.Prefix
      match r with
      | core.result.Result.Ok p =>
        let (elems, object_size) := p
        if object_size = size
        then ok (some elems)
        else ok none
      | core.result.Result.Err _ => ok none

end Zerocopy
