/- Copyright 2026 The Fuchsia Authors

Licensed under a BSD-style license <LICENSE-BSD>, Apache License, Version 2.0
<LICENSE-APACHE or https://www.apache.org/licenses/LICENSE-2.0>, or the MIT
license <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
This file may not be copied, modified, or distributed except according to
those terms. -/

-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zerocopy]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
module
public import Aeneas
public import Zerocopy.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open Zerocopy

/-- [core::mem::size_of]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 375:0-375:34
    Name pattern: [core::mem::size_of]
    Visibility: public -/
@[rust_fun "core::mem::size_of"]
axiom core.mem.size_of (T : Type) : Result Std.Usize

/-- [core::mem::align_of]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 543:0-543:35
    Name pattern: [core::mem::align_of]
    Visibility: public -/
@[rust_fun "core::mem::align_of"]
axiom core.mem.align_of (T : Type) : Result Std.Usize

/-- [core::num::niche_types::{impl core::clone::Clone for core::num::niche_types::NonZeroUsizeInner}::clone]:
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:17-17:22
    Name pattern: [core::num::niche_types::{core::clone::Clone<core::num::niche_types::NonZeroUsizeInner>}::clone]
    Visibility: public -/
@[rust_fun
  "core::num::niche_types::{core::clone::Clone<core::num::niche_types::NonZeroUsizeInner>}::clone"]
axiom core.num.niche_types.NonZeroUsizeInner.Insts.CoreCloneClone.clone
  :
  core.num.niche_types.NonZeroUsizeInner → Result
    core.num.niche_types.NonZeroUsizeInner

/-- [core::num::nonzero::{core::num::nonzero::NonZero<T, Clause0_NonZeroInner>}::new]:
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 388:4-388:42
    Name pattern: [core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::new]
    Visibility: public -/
@[rust_fun
  "core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::new"]
axiom core.num.nonzero.NonZero.new
  {T : Type} {Clause0_NonZeroInner : Type} (ZeroablePrimitiveInst :
  core.num.nonzero.ZeroablePrimitive T Clause0_NonZeroInner) :
  T → Result (Option (core.num.nonzero.NonZero T Clause0_NonZeroInner))

/-- [core::num::nonzero::{core::num::nonzero::NonZero<T, Clause0_NonZeroInner>}::get]:
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 467:4-467:31
    Name pattern: [core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::get]
    Visibility: public -/
@[rust_fun
  "core::num::nonzero::{core::num::nonzero::NonZero<@T, @Clause0_NonZeroInner>}::get"]
axiom core.num.nonzero.NonZero.get
  {T : Type} {Clause0_NonZeroInner : Type} (ZeroablePrimitiveInst :
  core.num.nonzero.ZeroablePrimitive T Clause0_NonZeroInner) :
  core.num.nonzero.NonZero T Clause0_NonZeroInner → Result T

/-- [core::num::{usize}::unchecked_add]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 1031:8-1031:66
    Name pattern: [core::num::{usize}::unchecked_add]
    Visibility: public -/
@[rust_fun "core::num::{usize}::unchecked_add"]
axiom core.num.Usize.unchecked_add
  : Std.Usize → Std.Usize → Result Std.Usize

/-- [core::num::{usize}::unchecked_mul]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 1419:8-1419:66
    Name pattern: [core::num::{usize}::unchecked_mul]
    Visibility: public -/
@[rust_fun "core::num::{usize}::unchecked_mul"]
axiom core.num.Usize.unchecked_mul
  : Std.Usize → Std.Usize → Result Std.Usize

