/- Copyright 2026 The Fuchsia Authors

Licensed under a BSD-style license <LICENSE-BSD>, Apache License, Version 2.0
<LICENSE-APACHE or https://www.apache.org/licenses/LICENSE-2.0>, or the MIT
license <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
This file may not be copied, modified, or distributed except according to
those terms. -/

-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zerocopy]: type definitions
module
public import Aeneas
public import Zerocopy.TypesExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace Zerocopy

/-- Trait declaration: [core::num::nonzero::ZeroablePrimitive]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 34:0-34:59
    Name pattern: [core::num::nonzero::ZeroablePrimitive]
    Visibility: public -/
@[rust_trait "core::num::nonzero::ZeroablePrimitive"
  (parentClauses := ["markerCopyInst", "innerCopyInst"])]
structure core.num.nonzero.ZeroablePrimitive (Self : Type) (Self_NonZeroInner :
  Type) where
  markerCopyInst : core.marker.Copy Self
  innerCopyInst : core.marker.Copy Self_NonZeroInner

/-- [zerocopy::layout::nested_reference::NestedLayer]
    Source: 'src/layout/nested_reference.rs', lines 31:0-35:1 -/
structure layout.nested_reference.NestedLayer where
  packed : Std.Usize
  min_align : Std.Usize
  prefix_bytes : Std.Usize

/-- [zerocopy::layout::RoundingAlignAndPhase]
    Source: 'src/layout.rs', lines 87:0-87:54 -/
structure layout.RoundingAlignAndPhase where
  _0 : core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner

/-- [zerocopy::layout::TrailingSliceLayout]
    Source: 'src/layout.rs', lines 194:0-248:1 -/
structure layout.TrailingSliceLayout (E : Type) where
  offset : Std.Usize
  elem_size : E
  size_base : Std.Usize
  size_rounding_align_and_phase : layout.RoundingAlignAndPhase

/-- [zerocopy::layout::SizeInfo]
    Source: 'src/layout.rs', lines 56:0-59:1 -/
@[discriminant isize]
inductive layout.SizeInfo (E : Type) where
| Sized : Std.Usize → layout.SizeInfo E
| SliceDst : layout.TrailingSliceLayout E → layout.SizeInfo E

/-- [zerocopy::layout::DstLayout]
    Source: 'src/layout.rs', lines 43:0-51:1
    Visibility: public -/
structure layout.DstLayout where
  align : core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner
  size_info : layout.SizeInfo Std.Usize
  statically_shallow_unpadded : Bool

end Zerocopy
