-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [probe]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace probe

/-- [probe::bump]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3731-charon-relocation-comment-provenance-2026-09-29/support/work/origin-root/src/lib.rs', lines 1:0-1:48
    Visibility: public -/
def bump (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 1#u32)

end probe
