//! Tests for macro expansion and interaction with Hermes specifications.

macro_rules! make_fn_with_spec {
    ($name:ident, $val:expr) => {
        /// @spec
        /// ensures: ret = $val
        pub fn $name() -> u32 {
            $val
        }
    };
}

// Function generated by a macro with an embedded spec.
make_fn_with_spec!(generated_fn, 42);

macro_rules! make_struct {
    ($name:ident) => {
        pub struct $name {
            pub f: u32,
        }
    };
}

// Struct generated by a macro.
make_struct!(GeneratedStruct);

pub mod hygiene {
    macro_rules! hygiene_check {
        () => {
            let x = 1;
            let x = x + 1;
        };
    }

    /// Tests macro hygiene and variable resolution.
    /// ```lean, hermes, spec
    /// proof:
    ///   sorry
    /// ```
    pub fn check_hygiene() {
        hygiene_check!();
    }
}

pub mod edge_cases {
    /// ```hermes
    /// isSafe : ∀ (self : Self), True
    /// ```
    pub unsafe trait MyTrait {
        fn foo();
    }

    macro_rules! decl_trait {
        ($n:ident) => {
            /// ```hermes
            /// isSafe : x > 0
            /// ```
            pub unsafe trait $n {
                fn bar();
            }
        }
    }

    // Macro invocation for trait declaration.
    decl_trait!(HiddenTrait);

    // Macro invocation with attributes.
    /// ```hermes
    /// context:
    /// -- Doc comment on macro invocation
    /// ```
    #[allow(dead_code)]
    decl_trait!(VisibleTrait);
}

/// ```lean, hermes
/// proof (h_progress):
///   sorry
/// proof context:
///   have h_foo : True := True.intro
/// ```
pub fn dummy_hermes_padding_10() {}

/// ```lean, hermes
/// proof (h_progress):
///   sorry
/// proof context:
///   have h_foo : True := True.intro
/// ```
pub fn dummy_hermes_padding_11() {}

