-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [probe]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace probe

/-- [probe::checked_add]:
    Source: '.anneal-local-tools/scratch/translation-goldens/probe.rs', lines 3:0-5:1
    Visibility: public -/
def checked_add (x : Std.U32) (y : Std.U32) : Result (Option Std.U32) := do
  ok (U32.checked_add x y)

/-- [probe::choose]:
    Source: '.anneal-local-tools/scratch/translation-goldens/probe.rs', lines 7:0-9:1
    Visibility: public -/
def choose
  (flag : Bool) (left : Std.U32) (right : Std.U32) : Result Std.U32 := do
  if flag
  then ok left
  else ok right

/-- [probe::bump]:
    Source: '.anneal-local-tools/scratch/translation-goldens/probe.rs', lines 11:0-13:1
    Visibility: public -/
def bump (value : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add value 1#u32)

end probe
