pub use std::env::*;

pub const PLAYGROUND_GITHUB_TOKEN: &str = "PLAYGROUND_GITHUB_TOKEN";
pub const PLAYGROUND_ANNEAL_PREWARM_STABLE: &str = "PLAYGROUND_ANNEAL_PREWARM_STABLE";
pub const PLAYGROUND_UI_ROOT: &str = "PLAYGROUND_UI_ROOT";
