import hashlib,json,os,stat,time
from pathlib import Path
from guard import ROOT,run
REPO=Path('<PROJECT>/.worktrees/anneal-v1-cleanup')
RC2=Path('<PROJECT>/.anneal-local-tools/scratch/20260927-reference-experiments/nix_toolchain_relocation/relocated_lean')
AENEAS=ROOT/'bundle/aeneas'; BACKEND=AENEAS/'backends/lean'
SLUG='ExpandOutputExpandOutput1d49e11e5683007f'
def environment(tool,case,immutable=None,trace=True):
    env=os.environ.copy()
    for key in ('CI','LEAN_PATH','LEAN_SRC_PATH','LEAN','LAKE_OVERRIDE_LEAN','LAKE_ARTIFACT_CACHE','LAKE_RESTORE_ARTIFACTS','LAKE_CACHE_DIR','DYLD_INSERT_LIBRARIES'):
        env.pop(key,None)
    env.update({'LEAN_SYSROOT':str(tool),'PATH':str(tool/'bin')+':'+env.get('PATH',''),'DYLD_LIBRARY_PATH':str(tool/'lib')+':'+str(tool/'lib/lean'),'MATHLIB_NO_CACHE_ON_UPDATE':'1','LAKE_CACHE_DIR':'','LAKE_ARTIFACT_CACHE':'false','LAKE_RESTORE_ARTIFACTS':'false','LEAN_NUM_THREADS':'1','HOME':str(ROOT/'home')})
    (ROOT/'home').mkdir(exist_ok=True)
    if trace:
        env.update({'DYLD_INSERT_LIBRARIES':str(ROOT/'trace.dylib'),'PROBE_TRACE_LOG':str(ROOT/'records'/(case+'.events.jsonl')),'PROBE_IMMUTABLE_ROOTS':str(immutable if immutable is not None else AENEAS)})
    return env
def command(case,tool,args,cwd,immutable=None,timeout=90,trace=True):
    record=run(case,[str(tool/'bin'/args[0]),*args[1:]],cwd,environment(tool,case,immutable,trace),timeout)
    events_path=ROOT/'records'/(case+'.events.jsonl')
    events=[json.loads(l) for l in events_path.read_text().splitlines()] if events_path.exists() else []
    result={'case':case,'exit':record['exit'],'abort':record['abort'],'elapsed_s':record['elapsed_s'],'loads':[e for e in events if e['kind']=='load'],'shared_attempts':[e for e in events if e['kind']=='mutation' and e['blocked']],'network_attempts':[e for e in events if e['kind']=='network'],'events':len(events)}
    with (ROOT/'cells.jsonl').open('a') as f:f.write(json.dumps(result)+'\n')
    print('CELL',json.dumps({k:v for k,v in result.items() if k!='loads'}),flush=True)
    return result
def manifest(workspace,root_name='anneal_verification',reverse=False):
    original=json.loads((BACKEND/'lake-manifest.json').read_text())
    packages=[{'type':'path','name':'aeneas','dir':os.path.relpath(BACKEND,workspace),'inherited':False}]
    inherited=[]
    for e in original['packages']:
        assert e['type']=='path'
        entry=dict(e);target=(BACKEND/e['dir']).resolve();assert target.is_relative_to(AENEAS)
        entry.update(dir=os.path.relpath(target,workspace),inherited=True);inherited.append(entry)
    if reverse:inherited.reverse()
    packages.extend(inherited)
    (workspace/'lake-manifest.json').write_text(json.dumps({'version':'1.2.0','packagesDir':'.lake/packages','packages':packages,'name':root_name,'lakeDir':'.lake','fixedToolchain':False},indent=2)+'\n')
def fixture(name,root_name='anneal_verification',reverse=False,seed=True):
    w=ROOT/'work'/name;gen=w/'generated'/SLUG;gen.mkdir(parents=True,exist_ok=True);(w/'anneal').mkdir(exist_ok=True)
    marker='-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS'
    snapshot=(REPO/'anneal/v1/tests/fixtures/expand_output/expected-aeneas.stdout').read_text().split(marker)
    assert len(snapshot)==3
    for kind,text in zip(('Types','Funs'),snapshot[1:]):(gen/(kind+'.lean')).write_text(marker+text.rstrip()+'\n')
    snapshot=(REPO/'anneal/v1/tests/fixtures/expand_output/expected-anneal.stdout').read_text()
    snapshot=snapshot[snapshot.index('-- This file is automatically generated by Anneal.'):].rstrip()+'\n'
    (gen/'Specs.lean').write_text(snapshot)
    (w/'anneal/Config.lean').write_text('')
    prelude='import Config\nimport Lean\n'+(REPO/'anneal/v1/src/Anneal.lean').read_text()+'\n\nopen Lean Elab Tactic Term\n\nelab (priority := high) "sorry" : tactic =>\n  throwError "The \'sorry\' tactic is forbidden; use --allow-sorry to allow it."\n\nelab (priority := high) "sorry" : term =>\n  throwError "The \'sorry\' term is forbidden; use --allow-sorry to allow it."\n'
    (w/'anneal/Anneal.lean').write_text(prelude)
    (w/'generated/Generated.lean').write_text(f'import {SLUG}.Funs\nimport {SLUG}.Types\n')
    (w/'lean-toolchain').write_text((BACKEND/'lean-toolchain').read_text())
    (w/'lakefile.lean').write_text(f'''import Lake
open Lake DSL
require aeneas from "{BACKEND}"
package {root_name}
@[default_target] lean_lib Generated where
  srcDir := "generated"
  roots := #[`Generated, `{SLUG}.Funs, `{SLUG}.Types]
@[default_target] lean_lib Anneal where
  srcDir := "anneal"
  roots := #[`Config, `Anneal]
''')
    if seed:manifest(w,root_name,reverse)
    return w
def snapshot(label,root=AENEAS,content=False):
    entries=[]
    for base,dirs,files in os.walk(root):
        for name in sorted([*dirs,*files]):
            p=Path(base)/name;s=p.lstat();row={'path':str(p.relative_to(root)),'mode':stat.S_IMODE(s.st_mode),'size':s.st_size,'mtime_ns':s.st_mtime_ns}
            if p.is_symlink():row['link']=os.readlink(p)
            elif p.is_file() and content:
                h=hashlib.sha256()
                with p.open('rb') as f:
                    while chunk:=f.read(1024*1024):h.update(chunk)
                row['sha256']=h.hexdigest()
            entries.append(row)
    entries.sort(key=lambda r:r['path']);(ROOT/(label+'.json')).write_text(json.dumps(entries)+'\n');return entries
if __name__=='__main__':
    w=fixture('pristine')
    command('rc2-trace-version',RC2,['lean','--version'],w)
    snapshot('archive-pristine-before',content=True)
    command('pristine-normal',RC2,['lake','--keep-toolchain','--no-cache','--verbose','build','Generated','Anneal'],w)
    w=fixture('pristine-old')
    command('pristine-old',RC2,['lake','--keep-toolchain','--no-cache','--old','--verbose','build','Generated','Anneal'],w)
    snapshot('archive-pristine-after',content=True)
    assert (ROOT/'archive-pristine-before.json').read_bytes()==(ROOT/'archive-pristine-after.json').read_bytes()
