-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [trait]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace trait

/-- Trait declaration: [trait::Step]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/trait/trait.rs', lines 2:0-2:40
    Visibility: public -/
structure Step (Self : Type) where
  step : Self → Result Std.U32

/-- [trait::{impl trait::Step for u32}::step]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/trait/trait.rs', lines 3:20-3:65
    Visibility: public -/
def U32.Insts.TraitStep.step (self : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add self 1#u32)

/-- Trait implementation: [trait::{impl trait::Step for u32}]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/trait/trait.rs', lines 3:0-3:67 -/
@[reducible]
def U32.Insts.TraitStep : Step Std.U32 := {
  step := U32.Insts.TraitStep.step
}

/-- [trait::use_step]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/trait/trait.rs', lines 4:0-4:43
    Visibility: public -/
def use_step (x : Std.U32) : Result Std.U32 := do
  U32.Insts.TraitStep.step x

end trait
