-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [trait_reuse]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace trait_reuse

/-- Trait declaration: [trait_reuse::core::Step]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-restricted-reuse-2026-09-29/support/work/fixture.rs', lines 3:4-3:44
    Visibility: public -/
structure core.Step (Self : Type) where
  step : Self → Result Std.U32

end trait_reuse
