/- Copyright 2026 The Fuchsia Authors

Licensed under a BSD-style license <LICENSE-BSD>, Apache License, Version 2.0
<LICENSE-APACHE or https://www.apache.org/licenses/LICENSE-2.0>, or the MIT
license <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
This file may not be copied, modified, or distributed except according to
those terms. -/

-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zerocopy]: function definitions
module
public import Aeneas
public import Zerocopy.Types
public import Zerocopy.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace Zerocopy

/-- Trait implementation: [core::num::niche_types::{impl core::clone::Clone for core::num::niche_types::NonZeroUsizeInner}]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:17-17:22
    Name pattern: [core::clone::Clone<core::num::niche_types::NonZeroUsizeInner>] -/
@[reducible, rust_trait_impl
  "core::clone::Clone<core::num::niche_types::NonZeroUsizeInner>"]
def core.num.niche_types.NonZeroUsizeInner.Insts.CoreCloneClone :
  core.clone.Clone core.num.niche_types.NonZeroUsizeInner := {
  clone := core.num.niche_types.NonZeroUsizeInner.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [core::num::niche_types::{impl core::marker::Copy for core::num::niche_types::NonZeroUsizeInner}]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:24-17:28
    Name pattern: [core::marker::Copy<core::num::niche_types::NonZeroUsizeInner>] -/
@[reducible, rust_trait_impl
  "core::marker::Copy<core::num::niche_types::NonZeroUsizeInner>"]
def core.num.niche_types.NonZeroUsizeInner.Insts.CoreMarkerCopy :
  core.marker.Copy core.num.niche_types.NonZeroUsizeInner := {
  cloneInst := core.num.niche_types.NonZeroUsizeInner.Insts.CoreCloneClone
}

/-- Trait implementation: [core::num::nonzero::{impl core::num::nonzero::ZeroablePrimitive<core::num::niche_types::NonZeroUsizeInner> for usize}]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 47:12-47:56
    Name pattern: [core::num::nonzero::ZeroablePrimitive<usize, core::num::niche_types::NonZeroUsizeInner>] -/
@[reducible, rust_trait_impl
  "core::num::nonzero::ZeroablePrimitive<usize, core::num::niche_types::NonZeroUsizeInner>"]
def Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner :
  core.num.nonzero.ZeroablePrimitive Std.Usize
  core.num.niche_types.NonZeroUsizeInner := {
  markerCopyInst := core.marker.CopyUsize
  innerCopyInst := core.num.niche_types.NonZeroUsizeInner.Insts.CoreMarkerCopy
}

/-- [zerocopy::layout::POINTER_WIDTH_BITS]
    Source: 'src/layout.rs', lines 17:0-17:62 -/
@[global_simps, irreducible]
def layout.POINTER_WIDTH_BITS : Result Std.Usize := do
  let i ← core.mem.size_of Std.Usize
  i * 8#usize

/-- [zerocopy::layout::{zerocopy::layout::RoundingAlignAndPhase}::new]:
    Source: 'src/layout.rs', lines 77:4-147:5 -/
@@AENEAS_GOLDEN("layout.RoundingAlignAndPhase.new.lean.in")@@

/-- [zerocopy::layout::{zerocopy::layout::RoundingAlignAndPhase}::components]:
    Source: 'src/layout.rs', lines 155:4-288:5 -/
@@AENEAS_GOLDEN("layout.RoundingAlignAndPhase.components.lean.in")@@

/-- [zerocopy::layout::{zerocopy::layout::RoundingAlignAndPhase}::align]:
    Source: 'src/layout.rs', lines 296:4-325:5 -/
@@AENEAS_GOLDEN("layout.RoundingAlignAndPhase.align.lean.in")@@

/-- [zerocopy::layout::{zerocopy::layout::SizeInfo<usize>}::try_to_nonzero_elem_size]:
    Source: 'src/layout.rs', lines 919:4-993:5 -/
@@AENEAS_GOLDEN("layout.SizeInfoUsize.try_to_nonzero_elem_size.lean.in")@@

/-- [zerocopy::layout::max_elems_for_bytes]:
    Source: 'src/layout.rs', lines 1013:0-1076:1 -/
@@AENEAS_GOLDEN("layout.max_elems_for_bytes.lean.in")@@

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::MIN_ALIGN]
    Source: 'src/layout.rs', lines 1096:4-1099:6 -/
@[global_simps, irreducible]
def layout.DstLayout.MIN_ALIGN
  :
  Result (core.num.nonzero.NonZero Std.Usize
    core.num.niche_types.NonZeroUsizeInner)
  := do
  let o ←
    core.num.nonzero.NonZero.new
      Usize.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroUsizeInner 1#usize
  match o with
  | none => fail panic
  | some min_align => ok min_align

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::assume_shallow_unpadded]:
    Source: 'src/layout.rs', lines 1160:4-1182:5 -/
@@AENEAS_GOLDEN("layout.DstLayout.assume_shallow_unpadded.lean.in")@@

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::new_zst]:
    Source: 'src/layout.rs', lines 1204:4-1269:5
    Visibility: public -/
@@AENEAS_GOLDEN("layout.DstLayout.new_zst.lean.in")@@

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::for_type]:
    Source: 'src/layout.rs', lines 1285:4-1346:5
    Visibility: public -/
@@AENEAS_GOLDEN("layout.DstLayout.for_type.lean.in")@@

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::for_unpadded_type]:
    Source: 'src/layout.rs', lines 1368:4-1402:5
    Visibility: public -/
@@AENEAS_GOLDEN("layout.DstLayout.for_unpadded_type.lean.in")@@

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::for_slice]:
    Source: 'src/layout.rs', lines 1416:4-1503:5 -/
@@AENEAS_GOLDEN("layout.DstLayout.for_slice.lean.in")@@

/-- [zerocopy::layout::{zerocopy::layout::DstLayout}::requires_static_padding]:
    Source: 'src/layout.rs', lines 1889:4-1912:5
    Visibility: public -/
@@AENEAS_GOLDEN("layout.DstLayout.requires_static_padding.lean.in")@@

/-- [zerocopy::util::padding_needed_for]:
    Source: 'src/util/mod.rs', lines 156:0-258:1 -/
@@AENEAS_GOLDEN("util.padding_needed_for.lean.in")@@

/-- [zerocopy::util::round_down_to_next_multiple_of_alignment]:
    Source: 'src/util/mod.rs', lines 279:0-336:1 -/
@@AENEAS_GOLDEN("util.round_down_to_next_multiple_of_alignment.lean.in")@@

/-- [zerocopy::util::max]:
    Source: 'src/util/mod.rs', lines 340:0-380:1 -/
@@AENEAS_GOLDEN("util.max.lean.in")@@

/-- [zerocopy::util::min]:
    Source: 'src/util/mod.rs', lines 384:0-424:1 -/
@@AENEAS_GOLDEN("util.min.lean.in")@@


end Zerocopy
