-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [identity_probe]: function definitions
import Aeneas
import Current.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace identity_probe

/-- [identity_probe::{impl core::clone::Clone for identity_probe::Wrap}::clone]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-identity-manifest-2026-09-29/support/work/source.rs', lines 2:9-2:14
    Visibility: public -/
def Wrap.Insts.CoreCloneClone.clone (self : Wrap) : Result Wrap := do
  ok self

/-- Trait implementation: [identity_probe::{impl core::clone::Clone for identity_probe::Wrap}]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-identity-manifest-2026-09-29/support/work/source.rs', lines 2:9-2:14 -/
@[reducible]
def Wrap.Insts.CoreCloneClone : core.clone.Clone Wrap := {
  clone := Wrap.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [identity_probe::{impl core::marker::Copy for identity_probe::Wrap}]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-identity-manifest-2026-09-29/support/work/source.rs', lines 2:16-2:20 -/
@[reducible]
def Wrap.Insts.CoreMarkerCopy : core.marker.Copy Wrap := {
  cloneInst := Wrap.Insts.CoreCloneClone
}

/-- [identity_probe::{impl identity_probe::Bump for identity_probe::Wrap}::bump]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-identity-manifest-2026-09-29/support/work/source.rs', lines 5:21-5:68
    Visibility: public -/
def Wrap.Insts.Identity_probeBump.bump (self : Wrap) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add self 1#u32)

/-- Trait implementation: [identity_probe::{impl identity_probe::Bump for identity_probe::Wrap}]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-identity-manifest-2026-09-29/support/work/source.rs', lines 5:0-5:70 -/
@[reducible]
def Wrap.Insts.Identity_probeBump : Bump Wrap := {
  bump := Wrap.Insts.Identity_probeBump.bump
}

/-- [identity_probe::use_bump]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-identity-manifest-2026-09-29/support/work/source.rs', lines 6:0-6:44
    Visibility: public -/
def use_bump (x : Wrap) : Result Std.U32 := do
  Wrap.Insts.Identity_probeBump.bump x

mutual

/-- [identity_probe::even]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-identity-manifest-2026-09-29/support/work/source.rs', lines 7:0-7:70
    Visibility: public -/
def even (n : Std.U32) : Result Bool := do
  if n = 0#u32
  then ok true
  else let i ← n - 1#u32
       odd i
partial_fixpoint

/-- [identity_probe::odd]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-identity-manifest-2026-09-29/support/work/source.rs', lines 8:0-8:71
    Visibility: public -/
def odd (n : Std.U32) : Result Bool := do
  if n = 0#u32
  then ok false
  else let i ← n - 1#u32
       even i
partial_fixpoint

end

end identity_probe
