# Copyright 2024 The Fuchsia Authors
#
# Licensed under a BSD-style license <LICENSE-BSD>, Apache License, Version 2.0
# <LICENSE-APACHE or https://www.apache.org/licenses/LICENSE-2.0>, or the MIT
# license <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
# This file may not be copied, modified, or distributed except according to
# those terms.

name: Resolve zerocopy toolchain version
inputs:
  toolchain:
    description: 'Toolchain name'
    required: true

runs:
  using: composite
  steps:
  - id: resolve
    shell: bash
    run: |
      # We use toolchain descriptors ("msrv", "stable", "nightly", and values
      # from the "metadata.build-rs" key in Cargo.toml) in the matrix. This
      # action converts this descriptor to a particular toolchain version by
      # looking up the corresponding key in `Cargo.toml`. It sets the
      # `ZC_TOOLCHAIN` environment variable for use in other GH Actions steps
      # that require variable interpolation, which doesn't support running
      # arbitrary commands. In other words, we can't rewrite:
      #
      #   foobar: $ {{ env.ZC_TOOLCHAIN }}
      #
      # ...to:
      #
      #   foobar: $ {{ ./cargo.sh --version matrix.toolchain }} # hypothetical syntax

      TOOLCHAIN="$(./cargo.sh --version ${{ inputs.toolchain }})"
      echo "toolchain=$TOOLCHAIN" >> $GITHUB_OUTPUT
