-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [snapshot_probe]: function definitions
import Aeneas
import A.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace snapshot_probe

/-- [snapshot_probe::step]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-charon-aeneas-boundary-2026-09-29/support/work/source.rs', lines 4:0-6:1
    Visibility: public -/
def step (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 1#u32)

/-- [snapshot_probe::select]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-charon-aeneas-boundary-2026-09-29/support/work/source.rs', lines 8:0-10:1
    Visibility: public -/
def select
  (flag : Bool) (left : Std.U32) (right : Std.U32) : Result Std.U32 := do
  if flag
  then ok left
  else ok right

end snapshot_probe
