-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [external_probe]: function definitions
import Aeneas
import Source.Types
import Source.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace external_probe

/-- [external_probe::external_call]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-external-model-without-codegen-change-2026-09-29/support/work/source.rs', lines 3:0-3:69
    Visibility: public -/
def external_call (x : Std.U32) : Result Std.U32 := do
  external_double x

end external_probe
