-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [r37u0]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Probe.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open r37u0

/-- [dep_a::dep_a]:
    Source: '/Users/josh/Codex/Meta/Data/20260929-issue-3730-3731/r42-run2/u0/dep_a/src/lib.rs', lines 1:0-1:24
    Name pattern: [dep_a::dep_a]
    Visibility: public -/
@[rust_fun "dep_a::dep_a"] axiom dep_a.dep_a : Std.U32 → Result Std.U32

/-- [dep_b::dep_b]:
    Source: '/Users/josh/Codex/Meta/Data/20260929-issue-3730-3731/r42-run2/u0/dep_b/src/lib.rs', lines 1:0-1:24
    Name pattern: [dep_b::dep_b]
    Visibility: public -/
@[rust_fun "dep_b::dep_b"] axiom dep_b.dep_b : Std.U32 → Result Std.U32

