-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [r37u0]: function definitions
import Aeneas
import Probe.Types
import Probe.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace r37u0

/-- [r37u0::combined]:
    Source: 'src/lib.rs', lines 1:0-1:74
    Visibility: public -/
def combined (x : Std.U32) : Result Std.U32 := do
  let i ← dep_a.dep_a x
  let i1 ← dep_b.dep_b x
  ok (core.num.U32.wrapping_add i i1)

end r37u0
