//! Tests for macro expansion and interaction with Anneal specifications.

macro_rules! make_fn_with_spec {
    ($name:ident, $val:expr) => {
        /// ```lean, anneal, spec
        /// -- FIXME: Remove manual sorry once we support omitting proofs
        /// theorem spec :
        ///   Aeneas.Std.WP.spec ($name) (fun ret_ => True) := by
        ///   sorry
        /// ```
        pub fn $name() -> u32 {
            $val
        }
    };
}

// Function generated by a macro with an embedded spec.
make_fn_with_spec!(generated_fn, 42);

macro_rules! make_struct {
    ($name:ident) => {
        pub struct $name {
            pub f: u32,
        }
    };
}

// Struct generated by a macro.
make_struct!(GeneratedStruct);

pub mod hygiene {
    macro_rules! hygiene_check {
        () => {
            let x = 1;
            let x = x + 1;
        };
    }

    /// Tests macro hygiene and variable resolution.
    /// ```lean, anneal, spec
    /// theorem spec :
    ///   Aeneas.Std.WP.spec (check_hygiene) (fun ret_ => True) := by
    ///   sorry
    /// ```
    pub fn check_hygiene() {
        hygiene_check!();
    }
}

pub mod edge_cases {
    /// ```lean, anneal
    /// def isSafe {Self : Type} (inst : MyTrait Self) : Prop := True
    /// ```
    pub unsafe trait MyTrait {
        fn foo();
    }

    macro_rules! decl_trait {
        ($n:ident) => {
            /// ```lean, anneal
            /// def isSafe {Self : Type} (inst : $n Self) : Prop := True
            /// ```
            pub unsafe trait $n {
                fn bar();
            }
        }
    }

    // Macro invocation for trait declaration.
    decl_trait!(HiddenTrait);

    // Macro invocation with attributes.
    /// ```anneal
    /// context:
    /// -- Doc comment on macro invocation
    /// ```
    #[allow(dead_code)]
    decl_trait!(VisibleTrait);
}

/// ```lean, anneal, spec
/// theorem spec :
///   Aeneas.Std.WP.spec (dummy_anneal_padding_10) (fun ret_ => True) := by
///   sorry
/// ```
pub fn dummy_anneal_padding_10() {}

/// ```lean, anneal, spec
/// theorem spec :
///   Aeneas.Std.WP.spec (dummy_anneal_padding_11) (fun ret_ => True) := by
///   sorry
/// ```
pub fn dummy_anneal_padding_11() {}

