-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [closure]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace closure

/-- [closure::captured::closure]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/closure/closure.rs', lines 2:41-2:67 -/
@[reducible]
def captured.closure := Std.U32

/-- [closure::captured::{impl core::ops::function::Fn<(u32,), u32> for closure::captured::closure<'_0>}::call]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/closure/closure.rs', lines 2:41-2:67 -/
def captured.closure.Insts.CoreOpsFunctionFnTupleU32U32.call
  (c : captured.closure) (tupled_args : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add c tupled_args)

/-- [closure::captured]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/closure/closure.rs', lines 2:0-2:75
    Visibility: public -/
def captured (x : Std.U32) : Result Std.U32 := do
  captured.closure.Insts.CoreOpsFunctionFnTupleU32U32.call x 2#u32

/-- [closure::captured::{impl core::ops::function::FnMut<(u32,), u32> for closure::captured::closure<'_0>}::call_mut]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/closure/closure.rs', lines 2:41-2:67 -/
def captured.closure.Insts.CoreOpsFunctionFnMutTupleU32U32.call_mut
  (state : captured.closure) (args : Std.U32) :
  Result (Std.U32 × captured.closure)
  := do
  let i ← captured.closure.Insts.CoreOpsFunctionFnTupleU32U32.call state args
  ok (i, state)

/-- [closure::captured::{impl core::ops::function::FnOnce<(u32,), u32> for closure::captured::closure<'_0>}::call_once]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/closure/closure.rs', lines 2:41-2:67 -/
def captured.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32.call_once
  (c : captured.closure) (i : Std.U32) : Result Std.U32 := do
  let (i1, _) ←
    captured.closure.Insts.CoreOpsFunctionFnMutTupleU32U32.call_mut c i
  ok i1

/-- Trait implementation: [closure::captured::{impl core::ops::function::FnOnce<(u32,), u32> for closure::captured::closure<'_0>}]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/closure/closure.rs', lines 2:41-2:67 -/
@[reducible]
def captured.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32 :
  core.ops.function.FnOnce captured.closure Std.U32 Std.U32 := {
  call_once :=
    captured.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32.call_once
}

/-- Trait implementation: [closure::captured::{impl core::ops::function::FnMut<(u32,), u32> for closure::captured::closure<'_0>}]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/closure/closure.rs', lines 2:41-2:67 -/
@[reducible]
def captured.closure.Insts.CoreOpsFunctionFnMutTupleU32U32 :
  core.ops.function.FnMut captured.closure Std.U32 Std.U32 := {
  FnOnceInst := captured.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32
  call_mut := captured.closure.Insts.CoreOpsFunctionFnMutTupleU32U32.call_mut
}

/-- Trait implementation: [closure::captured::{impl core::ops::function::Fn<(u32,), u32> for closure::captured::closure<'_0>}]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/closure/closure.rs', lines 2:41-2:67 -/
@[reducible]
def captured.closure.Insts.CoreOpsFunctionFnTupleU32U32 : core.ops.function.Fn
  captured.closure Std.U32 Std.U32 := {
  FnMutInst := captured.closure.Insts.CoreOpsFunctionFnMutTupleU32U32
  call := captured.closure.Insts.CoreOpsFunctionFnTupleU32U32.call
}

end closure
