-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [select_lib]: function definitions
import Aeneas
import SelectLibSelectLibbd5cd6e20844f316.Types
open Aeneas Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace select_lib

/- [select_lib::my_lib]:
   Source: 'src/lib.rs', lines 3:0-3:14 -/
def my_lib : Result Unit := do
  ok ()

end select_lib
