-- This file is automatically generated by Hermes.
-- Do not edit manually.

import Hermes
import Aeneas
import Aeneas.ScalarTac.ScalarTac
import «SelectLibSelectLibbd5cd6e20844f316».Funs
import «SelectLibSelectLibbd5cd6e20844f316».Types

set_option linter.dupNamespace false
open Aeneas Aeneas.Std Result
namespace select_lib

namespace my_lib


theorem spec :
  Hermes.SpecificationHolds (α := Unit) (my_lib) (fun _ => True) := by
  sorry

end my_lib

end select_lib
