-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [select_lib]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace select_lib

end select_lib
