-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [source_owned_probe]: function definitions
import Aeneas
import Source.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace source_owned_probe

/-- [source_owned_probe::step]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-source-owned-projection-diagnostic-matrix-2026-09-29/support/source.rs', lines 6:0-8:1
    Visibility: public -/
def step (x : Std.U32) : Result Std.U32 := do
  missingGeneratedModelName

/-- [source_owned_probe::select]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-source-owned-projection-diagnostic-matrix-2026-09-29/support/source.rs', lines 13:0-15:1
    Visibility: public -/
def select
  (flag : Bool) (left : Std.U32) (right : Std.U32) : Result Std.U32 := do
  if flag
  then ok left
  else ok right

/-- [source_owned_probe::macro_generated]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-source-owned-projection-diagnostic-matrix-2026-09-29/support/source.rs', lines 19:8-19:67
    Visibility: public -/
def macro_generated (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 3#u32)

end source_owned_probe
