-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [common_utils]: function definitions
import Aeneas
import PkgBCommonUtilsba65431d1cceb20.Types
open Aeneas Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace common_utils

/- [common_utils::utils_b]:
   Source: 'crates/b/src/lib.rs', lines 3:0-3:15 -/
def utils_b : Result Unit := do
  ok ()

end common_utils
