-- This file is automatically generated by Hermes.
-- Do not edit manually.

import Hermes
import Aeneas
import Aeneas.ScalarTac.ScalarTac
import «PkgBCommonUtils395a076f201f4b38».Funs
import «PkgBCommonUtils395a076f201f4b38».Types

open Aeneas Aeneas.Std Result
open common_utils

namespace utils_b


theorem spec :
  Hermes.SpecificationHolds (α := Unit) (utils_b) (fun _ => True) := by
  sorry

end utils_b

