-- This file is automatically generated by Hermes.
-- Do not edit manually.

import Hermes
import Aeneas
import Aeneas.ScalarTac.ScalarTac
import «PkgBCommonUtilscc950d671f22d9a5».Funs
import «PkgBCommonUtilscc950d671f22d9a5».Types

set_option linter.dupNamespace false
open Aeneas Aeneas.Std Result
namespace common_utils

namespace utils_b


theorem spec :
  Hermes.SpecificationHolds (α := Unit) (utils_b) (fun _ => True) := by
  sorry

end utils_b

end common_utils
