-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [common_utils]: function definitions
import Aeneas
import PkgACommonUtils6c598860167205d2.Types
open Aeneas Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace common_utils

/- [common_utils::utils_a]:
   Source: 'crates/a/src/lib.rs', lines 3:0-3:15 -/
def utils_a : Result Unit := do
  ok ()

end common_utils
