-- This file is automatically generated by Hermes.
-- Do not edit manually.

import Hermes
import Aeneas
import Aeneas.ScalarTac.ScalarTac
import «PkgACommonUtilsd50e1473985c7f47».Funs
import «PkgACommonUtilsd50e1473985c7f47».Types

open Aeneas Aeneas.Std Result
open common_utils

namespace utils_a


theorem spec :
  Hermes.SpecificationHolds (α := Unit) (utils_a) (fun _ => True) := by
  sorry

end utils_a

