-- This file is automatically generated by Hermes.
-- Do not edit manually.

import Hermes
import Aeneas
import Aeneas.ScalarTac.ScalarTac
import «PkgACommonUtils9705c3f2088aad16».Funs
import «PkgACommonUtils9705c3f2088aad16».Types

set_option linter.dupNamespace false
open Aeneas Aeneas.Std Result
namespace common_utils

namespace utils_a


theorem spec :
  Hermes.SpecificationHolds (α := Unit) (utils_a) (fun _ => True) := by
  sorry

end utils_a

end common_utils
