-- This file is automatically generated by Hermes.
-- Do not edit manually.

import Hermes
import Aeneas
import Aeneas.ScalarTac.ScalarTac
import «PkgACommonUtils9953cc26a4ebeb24».Funs
import «PkgACommonUtils9953cc26a4ebeb24».Types

open Aeneas Aeneas.Std Result
open common_utils

namespace utils_a


theorem spec :
  Hermes.SpecificationHolds (α := Unit) (utils_a) (fun _ => True) := by
  sorry

end utils_a

