import SdkIdentity
-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [expand_output]: function definitions
import Aeneas
import ExpandOutputExpandOutput1d49e11e5683007f.Types
noncomputable section

open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace expand_output

/-- [expand_output::foo]:
    Source: 'src/lib.rs', lines 3:0-3:15
    Visibility: public -/
def foo : Result Unit := do
  ok ()

end expand_output
