-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [handoff_probe]: function definitions
import Aeneas
import Source.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-re