// We define these codegen benchmarks in a dedicated `#![no_std]` crate rather
// than treating them as standard `[dev-dependencies]` of the main `zerocopy`
// crate. This isolation allows us to compile instruction set architecture
// targets like `thumbv7m` or `riscv32imc` without accidentally pulling in
// `std`-dependent test harness crates which causes hard cross-compilation
// failures.
#![no_std]
#[path = "../../../benches/read_from_bytes.rs"]
pub mod read_from_bytes;
#[path = "../../../benches/read_from_prefix.rs"]
pub mod read_from_prefix;
#[path = "../../../benches/read_from_suffix.rs"]
pub mod read_from_suffix;
#[path = "../../../benches/ref_from_bytes_dynamic_padding.rs"]
pub mod ref_from_bytes_dynamic_padding;
#[path = "../../../benches/ref_from_bytes_dynamic_size.rs"]
pub mod ref_from_bytes_dynamic_size;
#[path = "../../../benches/ref_from_bytes_static_size.rs"]
pub mod ref_from_bytes_static_size;
#[path = "../../../benches/ref_from_bytes_with_elems_dynamic_padding.rs"]
pub mod ref_from_bytes_with_elems_dynamic_padding;
#[path = "../../../benches/ref_from_bytes_with_elems_dynamic_size.rs"]
pub mod ref_from_bytes_with_elems_dynamic_size;
#[path = "../../../benches/ref_from_prefix_dynamic_padding.rs"]
pub mod ref_from_prefix_dynamic_padding;
#[path = "../../../benches/ref_from_prefix_dynamic_size.rs"]
pub mod ref_from_prefix_dynamic_size;
#[path = "../../../benches/ref_from_prefix_static_size.rs"]
pub mod ref_from_prefix_static_size;
#[path = "../../../benches/ref_from_prefix_with_elems_dynamic_padding.rs"]
pub mod ref_from_prefix_with_elems_dynamic_padding;
#[path = "../../../benches/ref_from_prefix_with_elems_dynamic_size.rs"]
pub mod ref_from_prefix_with_elems_dynamic_size;
#[path = "../../../benches/ref_from_suffix_dynamic_padding.rs"]
pub mod ref_from_suffix_dynamic_padding;
#[path = "../../../benches/ref_from_suffix_dynamic_size.rs"]
pub mod ref_from_suffix_dynamic_size;
#[path = "../../../benches/ref_from_suffix_static_size.rs"]
pub mod ref_from_suffix_static_size;
#[path = "../../../benches/ref_from_suffix_with_elems_dynamic_padding.rs"]
pub mod ref_from_suffix_with_elems_dynamic_padding;
#[path = "../../../benches/ref_from_suffix_with_elems_dynamic_size.rs"]
pub mod ref_from_suffix_with_elems_dynamic_size;
#[path = "../../../benches/transmute.rs"]
pub mod transmute;
#[path = "../../../benches/transmute_ref_dynamic_size.rs"]
pub mod transmute_ref_dynamic_size;
#[path = "../../../benches/transmute_ref_static_size.rs"]
pub mod transmute_ref_static_size;
#[path = "../../../benches/try_read_from_bytes.rs"]
pub mod try_read_from_bytes;
#[path = "../../../benches/try_read_from_prefix.rs"]
pub mod try_read_from_prefix;
#[path = "../../../benches/try_read_from_suffix.rs"]
pub mod try_read_from_suffix;
#[path = "../../../benches/try_ref_from_bytes_dynamic_padding.rs"]
pub mod try_ref_from_bytes_dynamic_padding;
#[path = "../../../benches/try_ref_from_bytes_dynamic_size.rs"]
pub mod try_ref_from_bytes_dynamic_size;
#[path = "../../../benches/try_ref_from_bytes_static_size.rs"]
pub mod try_ref_from_bytes_static_size;
#[path = "../../../benches/try_ref_from_bytes_with_elems_dynamic_padding.rs"]
pub mod try_ref_from_bytes_with_elems_dynamic_padding;
#[path = "../../../benches/try_ref_from_bytes_with_elems_dynamic_size.rs"]
pub mod try_ref_from_bytes_with_elems_dynamic_size;
#[path = "../../../benches/try_ref_from_prefix_dynamic_padding.rs"]
pub mod try_ref_from_prefix_dynamic_padding;
#[path = "../../../benches/try_ref_from_prefix_dynamic_size.rs"]
pub mod try_ref_from_prefix_dynamic_size;
#[path = "../../../benches/try_ref_from_prefix_static_size.rs"]
pub mod try_ref_from_prefix_static_size;
#[path = "../../../benches/try_ref_from_prefix_with_elems_dynamic_padding.rs"]
pub mod try_ref_from_prefix_with_elems_dynamic_padding;
#[path = "../../../benches/try_ref_from_prefix_with_elems_dynamic_size.rs"]
pub mod try_ref_from_prefix_with_elems_dynamic_size;
#[path = "../../../benches/try_ref_from_suffix_dynamic_padding.rs"]
pub mod try_ref_from_suffix_dynamic_padding;
#[path = "../../../benches/try_ref_from_suffix_dynamic_size.rs"]
pub mod try_ref_from_suffix_dynamic_size;
#[path = "../../../benches/try_ref_from_suffix_static_size.rs"]
pub mod try_ref_from_suffix_static_size;
#[path = "../../../benches/try_ref_from_suffix_with_elems_dynamic_padding.rs"]
pub mod try_ref_from_suffix_with_elems_dynamic_padding;
#[path = "../../../benches/try_ref_from_suffix_with_elems_dynamic_size.rs"]
pub mod try_ref_from_suffix_with_elems_dynamic_size;
#[path = "../../../benches/try_transmute.rs"]
pub mod try_transmute;
#[path = "../../../benches/try_transmute_ref_dynamic_size.rs"]
pub mod try_transmute_ref_dynamic_size;
#[path = "../../../benches/try_transmute_ref_static_size.rs"]
pub mod try_transmute_ref_static_size;
