-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [last_good_probe]: function definitions
import Aeneas
import Candidate.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace last_good_probe

/-- [last_good_probe::inc]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-last-good-model-after-rust-failure-2026-09-29/support/work/source.rs', lines 2:0-2:47
    Visibility: public -/
def inc (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 2#u32)

/-- [last_good_probe::bad]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-last-good-model-after-rust-failure-2026-09-29/support/work/source.rs', lines 3:0-3:50
    Visibility: public -/
def bad (ptr : ConstRawPtr Std.U32) : Result Std.U32 := do
  sorry

end last_good_probe
