-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [cancel_probe]: function definitions
import Aeneas
import Base.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace cancel_probe

/-- [cancel_probe::inc]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-cross-tool-active-cancellation-barriers-2026-09-29/support/work/charon/base.rs', lines 2:0-2:47
    Visibility: public -/
def inc (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 1#u32)

end cancel_probe
