-- This file is automatically generated by Hermes.
-- Do not edit manually.

import Hermes
import Aeneas
import Aeneas.ScalarTac.ScalarTac
import «AppApp1fa3d09f651b8c43».Funs
import «AppApp1fa3d09f651b8c43».Types

set_option linter.dupNamespace false
open Aeneas Aeneas.Std Result
namespace app

namespace main_logic


theorem spec :
  Hermes.SpecificationHolds (α := Unit) (main_logic) (fun _ => True) := by
  sorry

end main_logic

end app
