-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [app]: function definitions
import Aeneas
import AppApp1fa3d09f651b8c43.Types
import AppApp1fa3d09f651b8c43.FunsExternal
open Aeneas Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace app

/- [app::main_logic]:
   Source: 'crates/app/src/lib.rs', lines 3:0-5:1 -/
def main_logic : Result Unit := do
  dep.util

end app
