-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [app]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import AppApp1fa3d09f651b8c43.Types
open Aeneas Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
open app

/- [dep::util]:
   Source: '/usr/local/google/home/joshlf/workspace/zerocopy/hermes/tools/hermes/target/hermes-test-07gpsE/mixed_workspace/crates/dep/src/lib.rs', lines 1:0-1:13
   Name pattern: [dep::util] -/
@[rust_fun "dep::util"] axiom dep.util : Result Unit

