-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [snapshot_probe]: function definitions
import Aeneas
import Unsupported.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace snapshot_probe

/-- [snapshot_probe::read_raw]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-charon-aeneas-boundary-2026-09-29/support/work/source.rs', lines 3:0-6:1
    Visibility: public -/
def read_raw (ptr : ConstRawPtr Std.U32) : Result Std.U32 := do
  sorry

end snapshot_probe
