-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [trait_reuse]: function definitions
import Aeneas
import Fixture.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace trait_reuse

/-- [trait_reuse::core::{impl trait_reuse::core::Step for u32}::step]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-restricted-reuse-2026-09-29/support/work/fixture.rs', lines 4:24-4:85
    Visibility: public -/
def U32.Insts.Trait_reuseCoreStep.step
  (self : Std.U32) (delta : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add self delta)

/-- Trait implementation: [trait_reuse::core::{impl trait_reuse::core::Step for u32}]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-restricted-reuse-2026-09-29/support/work/fixture.rs', lines 4:4-4:87 -/
@[reducible]
def U32.Insts.Trait_reuseCoreStep : core.Step Std.U32 := {
  step := U32.Insts.Trait_reuseCoreStep.step
}

/-- [trait_reuse::core::use_step]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-restricted-reuse-2026-09-29/support/work/fixture.rs', lines 5:4-5:48
    Visibility: public -/
def core.use_step (x : Std.U32) : Result Std.U32 := do
  U32.Insts.Trait_reuseCoreStep.step x 1#u32

/-- [trait_reuse::side::untouched]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-restricted-reuse-2026-09-29/support/work/fixture.rs', lines 8:4-8:58
    Visibility: public -/
def side.untouched (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 10#u32)

/-- [trait_reuse::combine]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-restricted-reuse-2026-09-29/support/work/fixture.rs', lines 10:0-10:84
    Visibility: public -/
def combine (x : Std.U32) : Result Std.U32 := do
  let i ← core.use_step x
  let i1 ← side.untouched x
  ok (core.num.U32.wrapping_add i i1)

end trait_reuse
