-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [trait_probe]: function definitions
import Aeneas
import TraitProbe.Types
import TraitProbe.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace trait_probe

/-- [trait_probe::old]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 2:0-2:47
    Visibility: public -/
def old (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 2#u32)

/-- [trait_probe::{impl trait_probe::Step for u32}::step]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 4:20-4:65
    Visibility: public -/
def U32.Insts.Trait_probeStep.step (self : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add self 1#u32)

/-- Trait implementation: [trait_probe::{impl trait_probe::Step for u32}]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 4:0-4:67 -/
@[reducible]
def U32.Insts.Trait_probeStep : Step Std.U32 := {
  step := U32.Insts.Trait_probeStep.step
}

/-- [trait_probe::external_call]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 6:0-6:69
    Visibility: public -/
def external_call (x : Std.U32) : Result Std.U32 := do
  external_double x

/-- [trait_probe::use_step]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-trait-output-shrink-matrix-2026-09-29/support/work/trait_probe.rs', lines 7:0-7:43
    Visibility: public -/
def use_step (x : Std.U32) : Result Std.U32 := do
  U32.Insts.Trait_probeStep.step x

end trait_probe
