# This script reduces the size of the Anneal CI Docker image by removing unused
# compiled Mathlib artifacts (.olean, .c, .o, .ir, .olean.private, etc.).
#
# It parses a DOT file generated by `lake exe graph` to determine which Mathlib
# modules are transitively required by the project's roots, and deletes all
# other artifacts found in the Mathlib build directory. This is necessary
# because Mathlib is extremely large and only a small fraction of it is used by
# the tests, and we need to fit within the 14 GB limit of standard GitHub
# Actions runners.

import os
import re
import sys

def prune_mathlib(dot_file, mathlib_build_dir):
    print(f"Reading graph from {dot_file}...")
    with open(dot_file, 'r') as f:
        content = f.read()

    # Extract all Mathlib modules mentioned in the graph. We assume that any
    # module name starting with "Mathlib." in the DOT file represents a required
    # dependency.
    needed_modules = set(re.findall(r'"Mathlib\.[^"]*"', content))
    
    # Convert module names to relative paths that match the filesystem structure
    # of compiled artifacts. For example, "Mathlib.Data.Nat.Basic" becomes
    # "Data/Nat/Basic".
    needed_paths = set()
    for mod in needed_modules:
        mod_name = mod.strip('"')[len("Mathlib."):]
        rel_path = mod_name.replace('.', '/')
        needed_paths.add(rel_path)

    print(f"Found {len(needed_paths)} needed Mathlib modules.")

    # Locate the directory where compiled artifacts are stored.
    mathlib_lib_dir = os.path.join(mathlib_build_dir, ".lake", "build", "lib", "lean", "Mathlib")
    if not os.path.exists(mathlib_lib_dir):
         print(f"Mathlib lib dir not found: {mathlib_lib_dir}")
         return

    deleted_count = 0
    kept_count = 0

    # Recursively traverse the Mathlib build directory to find and prune unused
    # artifacts.
    for root, dirs, files in os.walk(mathlib_lib_dir):
        for file in files:
            if file.endswith('.olean'):
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, mathlib_lib_dir)
                rel_path_no_ext = os.path.splitext(rel_path)[0]

                if rel_path_no_ext not in needed_paths:
                    # Delete the .olean file.
                    os.remove(full_path)
                    deleted_count += 1
                    
                    # Also remove other artifact types associated with the
                    # module if they exist.
                    base_no_ext = os.path.splitext(full_path)[0]
                    
                    # Files named [FileName].[ext]
                    for ext in ['.c', '.o', '.ilean', '.trace', '.ir']:
                         p = base_no_ext + ext
                         if os.path.exists(p):
                              os.remove(p)
                              
                    # Files named [FileName].olean.[ext] (.private and .server
                    # files are named this way and take up significant space).
                    for ext in ['.private', '.server']:
                         p = full_path + ext
                         if os.path.exists(p):
                              os.remove(p)
                else:
                    kept_count += 1

    print(f"Pruning complete. Deleted {deleted_count} unused modules and their associated artifacts. Kept {kept_count} needed modules.")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 prune_mathlib.py <imports.dot> <mathlib_package_dir>")
        sys.exit(1)
    
    prune_mathlib(sys.argv[1], sys.argv[2])
