-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [v1_abs_probe]: function definitions
import Aeneas
import V1AbsProbeV1AbsProbea6d6c1948bec6cff.Types
noncomputable section

open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace v1_abs_probe

/-- [v1_abs_probe::abs]:
    Source: 'src/main.rs', lines 21:0-23:1
    Visibility: public -/
def abs (x : Std.I32) : Result Std.I32 := do
  if x < 0#i32
  then -. x
  else ok x

end v1_abs_probe
