-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [identity_probe]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace Alternate

/-- [identity_probe::Wrap]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-identity-manifest-2026-09-29/support/work/source.rs', lines 3:0-3:25
    Visibility: public -/
@[reducible]
def Wrap := Std.U32

/-- Trait declaration: [identity_probe::Bump]
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/reference-publish/reports/anneal-3730-aeneas-identity-manifest-2026-09-29/support/work/source.rs', lines 4:0-4:40
    Visibility: public -/
structure Bump (Self : Type) where
  bump : Self → Result Std.U32

end Alternate
