/- Copyright 2026 The Fuchsia Authors

Licensed under a BSD-style license <LICENSE-BSD>, Apache License, Version 2.0
<LICENSE-APACHE or https://www.apache.org/licenses/LICENSE-2.0>, or the MIT
license <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
This file may not be copied, modified, or distributed except according to
those terms. -/

module
public import Aeneas
public meta import Lean
public section

open Lean Aeneas Aeneas.Std

namespace AeneasSpecs

-- Record exactly the transparent propositions generated by `spec`, so the
-- upstream step adapter unfolds specifications without unfolding WP itself.
meta initialize specAttribute : TagAttribute ←
  registerTagAttribute `aeneas_spec "A transparent Aeneas specification"

declare_syntax_cat specRequirement
syntax "requires " ident " : " term : specRequirement

/-- A specification is a transparent proposition. Its separately supplied
proof establishes successful termination and the postcondition for every input
satisfying the named requirements. Inline Rust annotations omit `for`: tooling
inserts the fully qualified application using the enclosing Rust signature. -/
syntax (name := totalSpec) "spec " ident bracketedBinder* " for " term
  specRequirement* " ensures " term+ " => " term : command

/-- Partial specifications permit divergence, but exclude failure. -/
syntax (name := partialSpec) "partial " "spec " ident bracketedBinder* " for " term
  specRequirement* " ensures " term+ " => " term : command

syntax (name := viewSpec) "spec " ident bracketedBinder* " for " term
  specRequirement* " refines " term " to " term
  (" ensures " ident " => " term)? : command
syntax (name := partialViewSpec) "partial " "spec " ident bracketedBinder* " for " term
  specRequirement* " refines " term " to " term
  (" ensures " ident " => " term)? : command

private meta def quantifySpec (args : Array (TSyntax ``Lean.Parser.Term.bracketedBinder))
    (requirements : Array Syntax) (post : TSyntax `term) : MacroM (TSyntax `term) := do
  let mut body := post
  for requirement in requirements.reverse do
    match requirement with
    | `(specRequirement| requires $id:ident : $pre:term) =>
      body ← `(∀ ($id : ($pre : Prop)), $body)
    | _ => Macro.throwUnsupported
  for arg in args.reverse do
    body ← `(∀ $arg:bracketedBinder, $body)
  pure body

private meta def specDeclaration (id : TSyntax `ident) (body : TSyntax `term) : MacroM Syntax :=
  -- Requirement names are useful in proofs, even when the proposition does
  -- not refer to their proof values. Scope the linter setting to this abbrev.
  `(set_option linter.unusedVariables false in
    @[aeneas_spec] abbrev $id : Prop := $body)

macro_rules
  | `(spec $id:ident $args:bracketedBinder* for $call:term
      $requirements:specRequirement* refines $view:term to $model:term) => do
    let post : TSyntax `term ← `($call ⦃ r => $view r = $model ⦄)
    let body ← quantifySpec args requirements post
    specDeclaration id body

macro_rules
  | `(spec $id:ident $args:bracketedBinder* for $call:term
      $requirements:specRequirement* refines $view:term to $model:term
      ensures $r:ident => $post:term) => do
    let post : TSyntax `term ← `($call ⦃ $r => $view $r = $model ∧ $post ⦄)
    let body ← quantifySpec args requirements post
    specDeclaration id body

macro_rules
  | `(partial spec $id:ident $args:bracketedBinder* for $call:term
      $requirements:specRequirement* refines $view:term to $model:term) => do
    let post : TSyntax `term ← `($call ⦃ r => $view r = $model ⦄div)
    let body ← quantifySpec args requirements post
    specDeclaration id body

macro_rules
  | `(partial spec $id:ident $args:bracketedBinder* for $call:term
      $requirements:specRequirement* refines $view:term to $model:term
      ensures $r:ident => $post:term) => do
    let post : TSyntax `term ← `($call ⦃ $r => $view $r = $model ∧ $post ⦄div)
    let body ← quantifySpec args requirements post
    specDeclaration id body

macro_rules
  | `(spec $id:ident $args:bracketedBinder* for $call:term
      $requirements:specRequirement* ensures $x:term => $post:term) => do
    let post : TSyntax `term ← `($call ⦃ $x => $post ⦄)
    let body ← quantifySpec args requirements post
    specDeclaration id body

macro_rules
  | `(spec $id:ident $args:bracketedBinder* for $call:term
      $requirements:specRequirement* ensures $x:term $xs:term* => $post:term) => do
    let post : TSyntax `term ← `($call ⦃ $x $xs* => $post ⦄)
    let body ← quantifySpec args requirements post
    specDeclaration id body

macro_rules
  | `(partial spec $id:ident $args:bracketedBinder* for $call:term
      $requirements:specRequirement* ensures $x:term => $post:term) => do
    let post : TSyntax `term ← `($call ⦃ $x => $post ⦄div)
    let body ← quantifySpec args requirements post
    specDeclaration id body

macro_rules
  | `(partial spec $id:ident $args:bracketedBinder* for $call:term
      $requirements:specRequirement* ensures $x:term $xs:term* => $post:term) => do
    let post : TSyntax `term ← `($call ⦃ $x $xs* => $post ⦄div)
    let body ← quantifySpec args requirements post
    specDeclaration id body

/-- A generated fence contains exactly one specification command. Lean's
command parser accepts indented commands too, so indentation alone cannot keep
an annotation from introducing `open`, `namespace`, or other declarations that
change the context of subsequent specifications. The delimiters enforce one
command, and the syntax-kind check restricts that command to `spec`. -/
syntax "aeneas_spec_begin " command " aeneas_spec_end" : command

macro_rules
  | `(aeneas_spec_begin $declaration:command aeneas_spec_end) => do
    unless #[``totalSpec, ``partialSpec, ``viewSpec, ``partialViewSpec].contains
        declaration.raw.getKind do
      Macro.throwErrorAt declaration "An Aeneas fence must contain exactly one spec declaration"
    pure declaration.raw

/-- Check the elaborated proposition's connection to its Rust function. Textual
parameter names alone are insufficient: Lean can insert a coercion, or a later
binder can shadow an input. Inspect the elaborated expression without reducing
the application, so every argument must be the original input variable itself.
The generated command supplies the independently verified model declaration
and the number of Rust type and value parameters. Additional ghost inputs and
requirements may follow those parameters in the proposition's telescope. -/
elab "check_spec_binding " candidate:ident " for " model:ident " with " count:num : command =>
    Elab.Command.liftTermElabM do
  let specName ← Elab.realizeGlobalConstNoOverloadWithInfo candidate
  let modelName ← Elab.realizeGlobalConstNoOverloadWithInfo model
  let info ← getConstInfo specName
  let .defnInfo declaration := info
    | throwErrorAt candidate "Expected a specification declaration, got {specName}"
  unless specAttribute.hasTag (← getEnv) specName do
    throwErrorAt candidate "Expected a specification declaration, got {specName}"
  let inputCount := count.getNat
  Meta.forallTelescope declaration.value fun inputs body => do
    let body := body.consumeMData
    unless body.getAppFn.isConstOf ``WP.spec || body.getAppFn.isConstOf ``WP.dspec do
      throwErrorAt candidate "Specification {specName} does not directly state a total or partial contract"
    let contractArgs := body.getAppArgs
    unless contractArgs.size == 3 do
      throwErrorAt candidate "Specification {specName} has an unexpected contract application"
    let call := contractArgs[1]!.consumeMData
    unless call.getAppFn.isConstOf modelName do
      throwErrorAt candidate "Specification {specName} does not call the expected model {modelName}"
    let arguments := call.getAppArgs
    unless arguments.size == inputCount && inputs.size ≥ inputCount do
      throwErrorAt candidate "Specification {specName} does not bind exactly {inputCount} model inputs"
    for index in [:inputCount] do
      unless arguments[index]!.consumeMData == inputs[index]! do
        throwErrorAt candidate "Specification {specName} model input {index + 1} is not its original bound variable"

/-- Register an ordinary theorem whose type names a `spec` proposition with
Aeneas's existing step database. This pinned upstream registry inspects theorem
types syntactically. The generated alias expands only specifications, and Lean
checks its original theorem value against the expanded type. -/
elab "register_spec_step " candidate:ident : command => Elab.Command.liftCoreM do
  let thmName ← Elab.realizeGlobalConstNoOverloadWithInfo candidate
  let info ← getConstInfo thmName
  let .thmInfo _ := info
    | throwError "Expected a theorem, got {thmName}"
  let env ← getEnv
  let expanded ← Meta.deltaExpand info.type (specAttribute.hasTag env)
  let adapterName := thmName.appendAfter "_step"
  let declaration : TheoremVal := ⟨⟨adapterName, info.levelParams, expanded⟩,
    mkConst thmName (info.levelParams.map Level.param), [adapterName]⟩
  addDecl (.thmDecl declaration)
  Elab.addDeclarationRangesFromSyntax adapterName candidate
  Attribute.add adapterName `step .missing .global

end AeneasSpecs
