/- Copyright 2026 The Fuchsia Authors

Licensed under a BSD-style license <LICENSE-BSD>, Apache License, Version 2.0
<LICENSE-APACHE or https://www.apache.org/licenses/LICENSE-2.0>, or the MIT
license <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
This file may not be copied, modified, or distributed except according to
those terms. -/

module
public import Aeneas
public import Validity
public meta import Lean
public section

open Lean Aeneas Aeneas.Std

namespace AeneasSpecs

-- Record exactly the transparent propositions generated by `spec`, so the
-- upstream step adapter unfolds specifications without unfolding WP itself.
meta initialize specAttribute : TagAttribute ←
  registerTagAttribute `aeneas_spec "A transparent Aeneas specification"

declare_syntax_cat specRequirement
syntax "requires " ident " : " term : specRequirement

/-- Rust inputs are introduced from the verified model telescope, in its exact
order and with explicit binder annotations. Only mathematical ghosts are authored.
The generated type-parameter count is independently checked against Rust. -/
syntax (name := totalSpec) "spec " ident bracketedBinder* " for " term
  " with " num " type " "parameters"
  specRequirement* " ensures " term+ " => " term : command
syntax (name := partialSpec) "partial " "spec " ident bracketedBinder* " for " term
  " with " num " type " "parameters"
  specRequirement* " ensures " term+ " => " term : command
syntax (name := viewSpec) "spec " ident bracketedBinder* " for " term
  " with " num " type " "parameters"
  specRequirement* " refines " term " to " term
  (" ensures " ident " => " term)? : command
syntax (name := partialViewSpec) "partial " "spec " ident bracketedBinder* " for " term
  " with " num " type " "parameters"
  specRequirement* " refines " term " to " term
  (" ensures " ident " => " term)? : command

-- This term is produced only by the four command forms below. Resolve validity
-- in the original Rust context, and retain the selected expressions while ghosts
-- and their possible local instances are subsequently elaborated.
syntax (name := specBody) "aeneas_spec_body% " term " with " num " mode% " num
  " ghosts% " bracketedBinder* " requires% " specRequirement* " post% " term : term

private meta partial def simplifyValidity (p : Expr) : MetaM Expr := do
  let original := p
  let p ← Meta.withTransparency .all (Meta.whnf p)
  if p.isConstOf ``True then return p
  if let .forallE binderName domain body binderInfo := p then
    return ← Meta.withLocalDecl binderName binderInfo domain fun input => do
      let body ← simplifyValidity (body.instantiate1 input)
      if body.isConstOf ``True then return mkConst ``True
      Meta.mkForallFVars #[input] body
  if p.isAppOfArity ``And 2 then
    let args := p.getAppArgs
    let left ← simplifyValidity args[0]!
    let right ← simplifyValidity args[1]!
    if left.isConstOf ``True then return right
    if right.isConstOf ``True then return left
    return mkApp2 (mkConst ``And) left right
  -- Keep the accessor when an opaque dictionary or matcher blocks reduction.
  -- This retains its fixed instance while ordinary isValid lemmas can match it.
  if let .proj .. := p.getAppFn then return original
  if let .const matcher _ := p.getAppFn then
    if (← Meta.getMatcherInfo? matcher).isSome then return original
  return p

private meta def checkFreshNames (previous : Array Expr) (newInputs : Array Expr)
    : Elab.Term.TermElabM Unit := do
  let mut names ← previous.mapM fun e => return (← e.fvarId!.getDecl).userName.eraseMacroScopes
  for input in newInputs do
    let binderName := (← input.fvarId!.getDecl).userName.eraseMacroScopes
    if names.contains binderName then
      throwError "Specification binder {binderName} shadows an original input or an earlier binder"
    names := names.push binderName

private meta partial def withOriginalInputs (carrier : Expr) (inputs : Array Expr)
    (k : Array Expr → Expr → Elab.Term.TermElabM Expr) : Elab.Term.TermElabM Expr := do
  match carrier with
  | .forallE binderName domain body _ =>
    -- The model's names are intentionally used without fresh macro scopes, so
    -- authored references to x, self, and T resolve to these original inputs.
    Meta.withLocalDeclD binderName.eraseMacroScopes domain fun input => do
      checkFreshNames inputs #[input]
      withOriginalInputs (body.instantiate1 input) (inputs.push input) k
  | _ => k inputs carrier

private meta partial def withValidityDictionaries (genericInputs : Array Expr) (index : Nat)
    (dictionaries : Array Expr) (k : Array Expr → Elab.Term.TermElabM Expr)
    : Elab.Term.TermElabM Expr := do
  if h : index < genericInputs.size then
    let carrier ← Meta.mkAppM ``IsValid #[genericInputs[index]]
    let dictionaryName ← mkFreshUserName (Name.mkSimple s!"_rustValid{index}")
    Meta.withLocalDecl dictionaryName .instImplicit carrier fun dictionary =>
      withValidityDictionaries genericInputs (index + 1) (dictionaries.push dictionary) k
  else k dictionaries

private meta partial def withRequirements (requirements : Array Syntax) (index : Nat)
    (previous : Array Expr) (k : Array Expr → Elab.Term.TermElabM Expr)
    : Elab.Term.TermElabM Expr := do
  if h : index < requirements.size then
    match requirements[index] with
    | `(specRequirement| requires $id:ident : $pre:term) =>
      let carrier ← Elab.Term.elabTermEnsuringType pre (mkSort .zero)
      Meta.withLocalDeclD id.getId carrier fun hypothesis => do
        checkFreshNames previous #[hypothesis]
        withRequirements requirements (index + 1) (previous.push hypothesis) k
    | _ => Elab.throwUnsupportedSyntax
  else k previous

@[term_elab specBody] meta def elabSpecBody : Elab.Term.TermElab := fun stx _ => do
  match stx with
  | `(aeneas_spec_body% $model:term with $count:num mode% $modeNum:num
      ghosts% $ghosts:bracketedBinder* requires% $requirements:specRequirement* post% $authoredPost:term) =>
    let modelId ← match model with
      | `(@$id:ident) => pure id
      | `($id:ident) => pure id
      | _ => throwErrorAt model "A specification must name a bare model constant"
    let modelName ← Elab.realizeGlobalConstNoOverloadWithInfo modelId
    let modelExpr ← Meta.mkConstWithFreshMVarLevels modelName
    withOriginalInputs (← Meta.inferType modelExpr) #[] fun originals returnType => do
      unless count.getNat ≤ originals.size do
        throwErrorAt count "Model has fewer inputs than the supplied Rust type-parameter count"
      for input in originals[:count.getNat] do
        let carrier ← Meta.whnf (← Meta.inferType input)
        unless carrier.isSort && carrier != mkSort .zero do
          throwErrorAt count "Rust type parameters must be the original model's Type-valued prefix"
      for input in originals[count.getNat:] do
        if (← Meta.whnf (← Meta.inferType input)).isSort then
          throwErrorAt count "The supplied Rust type-parameter count omits a model type parameter"
      let returnType ← Meta.whnf returnType
      unless returnType.isAppOfArity ``Result 1 do
        throwErrorAt model "Model must return an Aeneas Result"
      let rawType := returnType.getAppArgs[0]!
      for input in originals[count.getNat:] do
        rejectEscapingFunctions (← Meta.inferType input)
      rejectEscapingFunctions rawType
      withValidityDictionaries (originals.extract 0 count.getNat) 0 #[] fun dictionaries => do
        let inputValidity ← (originals.extract count.getNat originals.size).mapM fun input => do
          simplifyValidity (← Meta.mkAppM ``IsValid.isValid #[input])
        let rawValidity ← Meta.withLocalDeclD `_raw rawType fun raw => do
          Meta.mkLambdaFVars #[raw] (← Meta.mkAppM ``IsValid.isValid #[raw])
        Elab.Term.elabBinders ghosts fun ghostInputs => do
          checkFreshNames originals ghostInputs
          -- Trivial concrete predicates contribute no extra assumptions. Generic
          -- dictionaries remain arbitrary predicates, including False.
          let hypotheses := inputValidity.filter (! ·.isConstOf ``True)
          let hypothesisDecls ← hypotheses.mapIdxM fun index carrier => do
            return (← mkFreshUserName (Name.mkSimple s!"_validInput{index}"), carrier)
          Meta.withLocalDeclsDND hypothesisDecls fun validityInputs => do
            let boundInputs := originals ++ dictionaries ++ ghostInputs ++ validityInputs
            withRequirements requirements 0 boundInputs fun allInputs => do
              let postType ← mkArrow rawType (mkSort .zero)
              let post ← Elab.Term.elabTermEnsuringType authoredPost postType
              let post ← Meta.withLocalDeclD `_raw rawType fun raw => do
                let valid ← simplifyValidity (mkApp rawValidity raw)
                let authored := mkApp post raw
                let combined := if valid.isConstOf ``True then authored
                  else mkApp2 (mkConst ``And) valid authored
                Meta.mkLambdaFVars #[raw] combined
              let call := mkAppN modelExpr originals
              let wp := if modeNum.getNat == 0 then ``WP.spec else ``WP.dspec
              let body ← Meta.mkAppM wp #[call, post]
              Elab.Term.levelMVarToParam (← Meta.mkForallFVars allInputs body)
  | _ => Elab.throwUnsupportedSyntax

private meta def specDeclaration (id : TSyntax `ident) (body : TSyntax `term) : MacroM Syntax :=
  `(set_option linter.unusedVariables false in
    @[aeneas_spec] abbrev $id : Prop := $body)

private meta def expandSpec (id : TSyntax `ident)
    (ghosts : Array (TSyntax ``Lean.Parser.Term.bracketedBinder))
    (model : TSyntax `term) (count : TSyntax `num) (isPartial : Bool)
    (requirements : Array (TSyntax `specRequirement)) (post : TSyntax `term) : MacroM Syntax := do
  let modeNum := Syntax.mkNumLit (if isPartial then "1" else "0")
  let body ← `(aeneas_spec_body% $model with $count mode% $modeNum:num
    ghosts% $ghosts:bracketedBinder* requires% $requirements:specRequirement* post% $post)
  specDeclaration id body

/-- Delegate authored result patterns to the pinned upstream notation, including
its shared type ascriptions and nested tuple patterns, then retain its predicate. -/
private meta def specPost (binders : List (TSyntax `term)) (body : TSyntax `term)
    : MacroM (TSyntax `term) := do
  let contract ← match binders with
    | [binder] => `(Result.ok () ⦃ $binder => $body ⦄)
    | binder :: rest => do
      let tail := rest.toArray
      `(Result.ok () ⦃ $binder $tail:term* => $body ⦄)
    | [] => Macro.throwUnsupported
  let some expanded ← expandMacro? contract.raw | Macro.throwUnsupported
  match expanded with
  | `(Aeneas.Std.WP.spec $_call $post) => pure post
  | _ => Macro.throwUnsupported

macro_rules
  | `(spec $id:ident $args:bracketedBinder* for $call:term with $count:num type parameters
      $requirements:specRequirement* ensures $x:term => $post:term) => do
    let post ← specPost [x] post
    expandSpec id args call count false requirements post
macro_rules
  | `(partial spec $id:ident $args:bracketedBinder* for $call:term with $count:num type parameters
      $requirements:specRequirement* ensures $x:term => $post:term) => do
    let post ← specPost [x] post
    expandSpec id args call count true requirements post
macro_rules
  | `(spec $id:ident $args:bracketedBinder* for $call:term with $count:num type parameters
      $requirements:specRequirement* ensures $x:term $xs:term* => $post:term) => do
    let post ← specPost (x :: xs.toList) post
    expandSpec id args call count false requirements post
macro_rules
  | `(partial spec $id:ident $args:bracketedBinder* for $call:term with $count:num type parameters
      $requirements:specRequirement* ensures $x:term $xs:term* => $post:term) => do
    let post ← specPost (x :: xs.toList) post
    expandSpec id args call count true requirements post
macro_rules
  | `(spec $id:ident $args:bracketedBinder* for $call:term with $count:num type parameters
      $requirements:specRequirement* refines $view:term to $expected:term) => do
    let post ← `(fun r => $view r = $expected)
    expandSpec id args call count false requirements post
macro_rules
  | `(partial spec $id:ident $args:bracketedBinder* for $call:term with $count:num type parameters
      $requirements:specRequirement* refines $view:term to $expected:term) => do
    let post ← `(fun r => $view r = $expected)
    expandSpec id args call count true requirements post
macro_rules
  | `(spec $id:ident $args:bracketedBinder* for $call:term with $count:num type parameters
      $requirements:specRequirement* refines $view:term to $expected:term
      ensures $r:ident => $post:term) => do
    let post ← `(fun $r => $view $r = $expected ∧ $post)
    expandSpec id args call count false requirements post
  | `(partial spec $id:ident $args:bracketedBinder* for $call:term with $count:num type parameters
      $requirements:specRequirement* refines $view:term to $expected:term
      ensures $r:ident => $post:term) => do
    let post ← `(fun $r => $view $r = $expected ∧ $post)
    expandSpec id args call count true requirements post

/-- A generated fence contains exactly one specification command. Lean's
command parser accepts indented commands too, so indentation alone cannot keep
an annotation from introducing `open`, `namespace`, or other declarations that
change the context of subsequent specifications. The delimiters enforce one
command, and the syntax-kind check restricts that command to `spec`. -/
syntax "aeneas_spec_begin " command " aeneas_spec_end" : command

macro_rules
  | `(aeneas_spec_begin $declaration:command aeneas_spec_end) => do
    unless #[``totalSpec, ``partialSpec, ``viewSpec, ``partialViewSpec].contains
        declaration.raw.getKind do
      Macro.throwErrorAt declaration "An Aeneas fence must contain exactly one spec declaration"
    pure declaration.raw

/-- Read a specification's actual model call without reducing the application.
Each argument must be its original prefix input variable; ghost inputs and
requirements may follow that prefix. Both the generated command and the final
coverage audit use this same elaborated-expression check. -/
meta def specBinding (specName : Name) : MetaM (Name × Nat) := do
  let info ← getConstInfo specName
  let .defnInfo declaration := info
    | throwError "Expected a specification declaration, got {specName}"
  unless specAttribute.hasTag (← getEnv) specName do
    throwError "Expected a specification declaration, got {specName}"
  Meta.forallTelescope declaration.value fun inputs body => do
    let body := body.consumeMData
    unless body.getAppFn.isConstOf ``WP.spec || body.getAppFn.isConstOf ``WP.dspec do
      throwError "Specification {specName} does not directly state a total or partial contract"
    let contractArgs := body.getAppArgs
    unless contractArgs.size == 3 do
      throwError "Specification {specName} has an unexpected contract application"
    let call := contractArgs[1]!.consumeMData
    let .const modelName _ := call.getAppFn
      | throwError "Specification {specName} does not directly call a model declaration"
    let arguments := call.getAppArgs
    unless inputs.size ≥ arguments.size do
      throwError "Specification {specName} has more model arguments than bound inputs"
    for index in [:arguments.size] do
      unless arguments[index]!.consumeMData == inputs[index]! do
        throwError "Specification {specName} model input {index + 1} is not its original bound variable"
    pure (modelName, arguments.size)

/-- Check the actual call against the independently verified model declaration
and Rust type/value parameter count supplied by the generated command. -/
elab "check_spec_binding " candidate:ident " for " model:ident " with " count:num : command =>
    Elab.Command.liftTermElabM do
  let specName ← Elab.realizeGlobalConstNoOverloadWithInfo candidate
  let modelName ← Elab.realizeGlobalConstNoOverloadWithInfo model
  let (actualModel, inputCount) ← withRef candidate (specBinding specName)
  unless actualModel == modelName do
    throwErrorAt candidate "Specification {specName} does not call the expected model {modelName}"
  unless inputCount == count.getNat do
    throwErrorAt candidate "Specification {specName} does not bind exactly {count.getNat} model inputs"

/-- Register an ordinary theorem whose type names a `spec` proposition with
Aeneas's existing step database. This pinned upstream registry inspects theorem
types syntactically. The generated alias expands only specifications, and Lean
checks its original theorem value against the expanded type. -/
elab "register_spec_step " candidate:ident : command => Elab.Command.liftCoreM do
  let thmName ← Elab.realizeGlobalConstNoOverloadWithInfo candidate
  let info ← getConstInfo thmName
  let .thmInfo _ := info
    | throwError "Expected a theorem, got {thmName}"
  let env ← getEnv
  let expanded ← Meta.deltaExpand info.type (specAttribute.hasTag env)
  let adapterName := thmName.appendAfter "_step"
  let declaration : TheoremVal := ⟨⟨adapterName, info.levelParams, expanded⟩,
    mkConst thmName (info.levelParams.map Level.param), [adapterName]⟩
  addDecl (.thmDecl declaration)
  Elab.addDeclarationRangesFromSyntax adapterName candidate
  Attribute.add adapterName `step .missing .global

end AeneasSpecs
