-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [baseline]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace refprobe

/-- [baseline::choose]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/baseline/baseline.rs', lines 2:0-2:71
    Visibility: public -/
def choose (b : Bool) (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  if b
  then ok x
  else ok y

/-- [baseline::bump]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/baseline/baseline.rs', lines 3:0-3:52
    Visibility: public -/
def bump (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 1#u32)

end refprobe
