-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [i148_corpus]: function definitions
import Aeneas
import Probe.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace i148_corpus

/-- [i148_corpus::add_one]:
    Source: 'src/lib.rs', lines 6:0-8:1
    Visibility: public -/
def add_one (x : Std.U32) : Result Std.U32 := do
  x + 1#u32

/-- [i148_corpus::choose]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def choose (flag : Bool) (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  if flag
  then ok x
  else ok y

/-- [i148_corpus::pair_sum]:
    Source: 'src/lib.rs', lines 14:0-16:1
    Visibility: public -/
def pair_sum (pair : Pair) : Result Std.U32 := do
  pair.left + pair.right

/-- [i148_corpus::make_pair]:
    Source: 'src/lib.rs', lines 18:0-20:1
    Visibility: public -/
def make_pair (x : Std.U32) (y : Std.U32) : Result Pair := do
  ok { left := x, right := y }

/-- [i148_corpus::combine]:
    Source: 'src/lib.rs', lines 22:0-25:1
    Visibility: public -/
def combine (flag : Bool) (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  let p ← make_pair x y
  let i ← choose flag p.left p.right
  add_one i

end i148_corpus
