-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [i148_corpus]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace i148_corpus

/-- [i148_corpus::Pair]
    Source: 'src/lib.rs', lines 1:0-4:1
    Visibility: public -/
structure Pair where
  left : Std.U32
  right : Std.U32

end i148_corpus
