-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [names]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace names

/-- [names::alpha::tick]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/names/names.rs', lines 2:16-2:64
    Visibility: public -/
def alpha.tick (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 1#u32)

/-- [names::beta::tick]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/names/names.rs', lines 3:15-3:63
    Visibility: public -/
def beta.tick (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 2#u32)

/-- [names::call]:
    Source: '/Users/josh/Codex/Projects/zerocopy/.anneal-local-tools/scratch/20260927-reference-experiments/aeneas_charon/cases/names/names.rs', lines 4:0-4:45
    Visibility: public -/
def call (x : Std.U32) : Result Std.U32 := do
  alpha.tick x

end names
