-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [golden_vertical]: function definitions
import Aeneas
import Current.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace golden_vertical

/-- [golden_vertical::inc]:
    Source: 'src/lib.rs', lines 3:0-3:47
    Visibility: public -/
def inc (x : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x 1#u32)

/-- [golden_vertical::twice]:
    Source: 'src/lib.rs', lines 5:0-5:43
    Visibility: public -/
def twice (x : Std.U32) : Result Std.U32 := do
  let i ← inc x
  inc i

/-- [golden_vertical::choose]:
    Source: 'src/lib.rs', lines 7:0-7:71
    Visibility: public -/
def choose (x : Std.U32) : Result Std.U32 := do
  if x = 0#u32
  then twice 1#u32
  else inc x

end golden_vertical
