// Copyright 2025 The Fuchsia Authors
//
// Licensed under a BSD-style license <LICENSE-BSD>, Apache License, Version 2.0
// <LICENSE-APACHE or https://www.apache.org/licenses/LICENSE-2.0>, or the MIT
// license <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
// This file may not be copied, modified, or distributed except according to
// those terms.

// WARNING: DO NOT EDIT THIS FILE. It is generated automatically. Edits should be
// made in `tools/codegen`.

// Do not lint generated code.
#![allow(warnings)]
#![allow(
    clippy::all,
    clippy::correctness,
    clippy::suspicious,
    clippy::style,
    clippy::complexity,
    clippy::perf,
    clippy::pedantic,
    clippy::restriction,
    clippy::nursery
)]

#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A> crate::Immutable for (A,)
where
    A: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B> crate::Immutable for (A, B)
where
    A: crate::Immutable,
    B: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C> crate::Immutable for (A, B, C)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D> crate::Immutable for (A, B, C, D)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E> crate::Immutable for (A, B, C, D, E)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F> crate::Immutable for (A, B, C, D, E, F)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G> crate::Immutable for (A, B, C, D, E, F, G)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H> crate::Immutable for (A, B, C, D, E, F, G, H)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I> crate::Immutable for (A, B, C, D, E, F, G, H, I)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J> crate::Immutable for (A, B, C, D, E, F, G, H, I, J)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K> crate::Immutable for (A, B, C, D, E, F, G, H, I, J, K)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
    Q: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
    Q: crate::Immutable,
    R: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
    Q: crate::Immutable,
    R: crate::Immutable,
    S: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
    Q: crate::Immutable,
    R: crate::Immutable,
    S: crate::Immutable,
    T: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
    Q: crate::Immutable,
    R: crate::Immutable,
    S: crate::Immutable,
    T: crate::Immutable,
    U: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
    Q: crate::Immutable,
    R: crate::Immutable,
    S: crate::Immutable,
    T: crate::Immutable,
    U: crate::Immutable,
    V: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
    Q: crate::Immutable,
    R: crate::Immutable,
    S: crate::Immutable,
    T: crate::Immutable,
    U: crate::Immutable,
    V: crate::Immutable,
    W: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X> crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
    Q: crate::Immutable,
    R: crate::Immutable,
    S: crate::Immutable,
    T: crate::Immutable,
    U: crate::Immutable,
    V: crate::Immutable,
    W: crate::Immutable,
    X: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y>
    crate::Immutable for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
    Q: crate::Immutable,
    R: crate::Immutable,
    S: crate::Immutable,
    T: crate::Immutable,
    U: crate::Immutable,
    V: crate::Immutable,
    W: crate::Immutable,
    X: crate::Immutable,
    Y: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
#[allow(deprecated, non_local_definitions)]
#[automatically_derived]
unsafe impl<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z>
    crate::Immutable
    for (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z)
where
    A: crate::Immutable,
    B: crate::Immutable,
    C: crate::Immutable,
    D: crate::Immutable,
    E: crate::Immutable,
    F: crate::Immutable,
    G: crate::Immutable,
    H: crate::Immutable,
    I: crate::Immutable,
    J: crate::Immutable,
    K: crate::Immutable,
    L: crate::Immutable,
    M: crate::Immutable,
    N: crate::Immutable,
    O: crate::Immutable,
    P: crate::Immutable,
    Q: crate::Immutable,
    R: crate::Immutable,
    S: crate::Immutable,
    T: crate::Immutable,
    U: crate::Immutable,
    V: crate::Immutable,
    W: crate::Immutable,
    X: crate::Immutable,
    Y: crate::Immutable,
    Z: crate::Immutable,
{
    fn only_derive_is_allowed_to_implement_this_trait() {}
}
