-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [coverage_app]: function definitions
import Aeneas
import CoverageApp.Types
import CoverageApp.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace CoverageApp

/-- [coverage_app::BUILD_VALUE]
    Source: '<workspace>/target/aarch64-apple-darwin/debug/build/coverage_app-95ecbc77b30b5a91/out/generated.rs', lines 1:0-1:32
    Visibility: public -/
@[global_simps, irreducible] def BUILD_VALUE : Std.U32 := 17#u32

/-- [coverage_app::proc_generated]:
    Source: 'coverage_app/src/lib.rs', lines 1:0-1:31
    Visibility: public -/
def proc_generated : Result Std.U32 := do
  ok 29#u32

/-- [coverage_app::library_subject]:
    Source: 'coverage_app/src/lib.rs', lines 4:0-4:91
    Visibility: public -/
def library_subject : Result Std.U32 := do
  let i ← shared.target_value
  let i1 ← i + BUILD_VALUE
  let i2 ← proc_generated
  i1 + i2

/-- [coverage_app::selected_feature_subject]:
    Source: 'coverage_app/src/lib.rs', lines 7:0-7:48
    Visibility: public -/
def selected_feature_subject : Result Std.U32 := do
  ok 101#u32

end CoverageApp
